#Server Configuration
server:
  port:

#Database Configuration
database:
  username:
  password:
  name:
  host:
  port:

#JWT Configuration
jwt:
  secret-key:

#Simple Storage Service (S3)
s3:
  access-key:
  secret-key:
  region:
  bucket: