// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository.go
//
// Generated by this command:
//
// 	mockgen -source=./repository.go -destination=../../mocks/rank/repository_mock.go
//

package mock_rank

import (
	context "context"
	reflect "reflect"

	rank "github.com/project-ippl-dev/tanding-api/internal/rank"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// EventParticipantFetchExcludeRegistrationID mocks base method.
func (m *MockRepository) EventParticipantFetchExcludeRegistrationID(ctx context.Context, arg rank.EventParticipantFetchExcludeRegistrationIDParams) ([]rank.EventParticipantFetchExcludeRegistrationIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventParticipantFetchExcludeRegistrationID", ctx, arg)
	ret0, _ := ret[0].([]rank.EventParticipantFetchExcludeRegistrationIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EventParticipantFetchExcludeRegistrationID indicates an expected call of EventParticipantFetchExcludeRegistrationID.
func (mr *MockRepositoryMockRecorder) EventParticipantFetchExcludeRegistrationID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventParticipantFetchExcludeRegistrationID", reflect.TypeOf((*MockRepository)(nil).EventParticipantFetchExcludeRegistrationID), ctx, arg)
}

// RankFetchPowerList mocks base method.
func (m *MockRepository) RankFetchPowerList(ctx context.Context, arg interface{}) ([]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RankFetchPowerList", ctx, arg)
	ret0, _ := ret[0].([]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RankFetchPowerList indicates an expected call of RankFetchPowerList.
func (mr *MockRepositoryMockRecorder) RankFetchPowerList(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RankFetchPowerList", reflect.TypeOf((*MockRepository)(nil).RankFetchPowerList), ctx, arg)
}

// RankCountPowerList mocks base method.
func (m *MockRepository) RankCountPowerList(ctx context.Context, sportID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RankCountPowerList", ctx, sportID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RankCountPowerList indicates an expected call of RankCountPowerList.
func (mr *MockRepositoryMockRecorder) RankCountPowerList(ctx, sportID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RankCountPowerList", reflect.TypeOf((*MockRepository)(nil).RankCountPowerList), ctx, sportID)
}

// RankFetchAllPointUser mocks base method.
func (m *MockRepository) RankFetchAllPointUser(ctx context.Context, arg interface{}) ([]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RankFetchAllPointUser", ctx, arg)
	ret0, _ := ret[0].([]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RankFetchAllPointUser indicates an expected call of RankFetchAllPointUser.
func (mr *MockRepositoryMockRecorder) RankFetchAllPointUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RankFetchAllPointUser", reflect.TypeOf((*MockRepository)(nil).RankFetchAllPointUser), ctx, arg)
}

// RankCountAllPointUser mocks base method.
func (m *MockRepository) RankCountAllPointUser(ctx context.Context, sportID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RankCountAllPointUser", ctx, sportID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RankCountAllPointUser indicates an expected call of RankCountAllPointUser.
func (mr *MockRepositoryMockRecorder) RankCountAllPointUser(ctx, sportID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RankCountAllPointUser", reflect.TypeOf((*MockRepository)(nil).RankCountAllPointUser), ctx, sportID)
}
