// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase.go
//
// Generated by this command:
//
//	mockgen -source=./usecase.go -destination=../../mocks/rank/usecase_mock.go
//

// Package mock_rank is a generated GoMock package.
package mock_rank

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	rank "github.com/project-ippl-dev/tanding-api/internal/rank"
	tools "github.com/project-ippl-dev/tanding-api/internal/tools"
	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// FetchByClubID mocks base method.
func (m *MockUsecase) FetchByClubID(ctx context.Context, clubID uuid.UUID) (rank.FetchByClubIDResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByClubID", ctx, clubID)
	ret0, _ := ret[0].(rank.FetchByClubIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByClubID indicates an expected call of FetchByClubID.
func (mr *MockUsecaseMockRecorder) FetchByClubID(ctx, clubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByClubID", reflect.TypeOf((*MockUsecase)(nil).FetchByClubID), ctx, clubID)
}

// FetchOwnPoint mocks base method.
func (m *MockUsecase) FetchOwnPoint(ctx context.Context, userID string) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOwnPoint", ctx, userID)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOwnPoint indicates an expected call of FetchOwnPoint.
func (mr *MockUsecaseMockRecorder) FetchOwnPoint(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOwnPoint", reflect.TypeOf((*MockUsecase)(nil).FetchOwnPoint), ctx, userID)
}

// Rank mocks base method.
func (m *MockUsecase) Rank(ctx context.Context, page, pageSize int32, arg rank.RankParams) (tools.Pagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rank", ctx, page, pageSize, arg)
	ret0, _ := ret[0].(tools.Pagination)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rank indicates an expected call of Rank.
func (mr *MockUsecaseMockRecorder) Rank(ctx, page, pageSize, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rank", reflect.TypeOf((*MockUsecase)(nil).Rank), ctx, page, pageSize, arg)
}

// Summary mocks base method.
func (m *MockUsecase) Summary(ctx context.Context, eventID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Summary", ctx, eventID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Summary indicates an expected call of Summary.
func (mr *MockUsecaseMockRecorder) Summary(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summary", reflect.TypeOf((*MockUsecase)(nil).Summary), ctx, eventID)
}

// UserRank mocks base method.
func (m *MockUsecase) UserRank(ctx context.Context, page, pageSize int32, arg rank.RankParams) (tools.Pagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserRank", ctx, page, pageSize, arg)
	ret0, _ := ret[0].(tools.Pagination)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserRank indicates an expected call of UserRank.
func (mr *MockUsecaseMockRecorder) UserRank(ctx, page, pageSize, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserRank", reflect.TypeOf((*MockUsecase)(nil).UserRank), ctx, page, pageSize, arg)
}
