// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase.go
//
// Generated by this command:
//
//	mockgen -source=./usecase.go -destination=../../mocks/certificate/usecase_mock.go
//

// Package mock_certificate is a generated GoMock package.
package mock_certificate

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	certificate "github.com/project-ippl-dev/tanding-api/internal/certificate"
	tools "github.com/project-ippl-dev/tanding-api/internal/tools"
	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// FetchByClubID mocks base method.
func (m *MockUsecase) FetchByClubID(ctx context.Context, page, pageSize int32, clubID uuid.UUID) (tools.Pagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByClubID", ctx, page, pageSize, clubID)
	ret0, _ := ret[0].(tools.Pagination)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByClubID indicates an expected call of FetchByClubID.
func (mr *MockUsecaseMockRecorder) FetchByClubID(ctx, page, pageSize, clubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByClubID", reflect.TypeOf((*MockUsecase)(nil).FetchByClubID), ctx, page, pageSize, clubID)
}

// FetchByUserID mocks base method.
func (m *MockUsecase) FetchByUserID(ctx context.Context, page, pageSize int32, userID string) (tools.Pagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByUserID", ctx, page, pageSize, userID)
	ret0, _ := ret[0].(tools.Pagination)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByUserID indicates an expected call of FetchByUserID.
func (mr *MockUsecaseMockRecorder) FetchByUserID(ctx, page, pageSize, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByUserID", reflect.TypeOf((*MockUsecase)(nil).FetchByUserID), ctx, page, pageSize, userID)
}

// FetchOne mocks base method.
func (m *MockUsecase) FetchOne(ctx context.Context, certificateID uuid.UUID) (certificate.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOne", ctx, certificateID)
	ret0, _ := ret[0].(certificate.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOne indicates an expected call of FetchOne.
func (mr *MockUsecaseMockRecorder) FetchOne(ctx, certificateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOne", reflect.TypeOf((*MockUsecase)(nil).FetchOne), ctx, certificateID)
}
