// Code generated by MockGen. DO NOT EDIT.
// Source: ./jwt.go
//
// Generated by this command:
//
//	mockgen -source=./jwt.go -destination=../../mocks/tools/jwt_mock.go
//

// Package mock_tools is a generated GoMock package.
package mock_tools

import (
	reflect "reflect"

	echo "github.com/labstack/echo/v4"
	tools "github.com/project-ippl-dev/tanding-api/internal/tools"
	gomock "go.uber.org/mock/gomock"
)

// MockJWTClient is a mock of JWTClient interface.
type MockJWTClient struct {
	ctrl     *gomock.Controller
	recorder *MockJWTClientMockRecorder
}

// MockJWTClientMockRecorder is the mock recorder for MockJWTClient.
type MockJWTClientMockRecorder struct {
	mock *MockJWTClient
}

// NewMockJWTClient creates a new mock instance.
func NewMockJWTClient(ctrl *gomock.Controller) *MockJWTClient {
	mock := &MockJWTClient{ctrl: ctrl}
	mock.recorder = &MockJWTClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTClient) EXPECT() *MockJWTClientMockRecorder {
	return m.recorder
}

// Auth mocks base method.
func (m *MockJWTClient) Auth() echo.MiddlewareFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Auth")
	ret0, _ := ret[0].(echo.MiddlewareFunc)
	return ret0
}

// Auth indicates an expected call of Auth.
func (mr *MockJWTClientMockRecorder) Auth() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Auth", reflect.TypeOf((*MockJWTClient)(nil).Auth))
}

// CreateToken mocks base method.
func (m *MockJWTClient) CreateToken(req tools.JWT) (tools.JWTResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", req)
	ret0, _ := ret[0].(tools.JWTResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockJWTClientMockRecorder) CreateToken(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockJWTClient)(nil).CreateToken), req)
}

// Decode mocks base method.
func (m *MockJWTClient) Decode(c echo.Context) tools.JWT {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", c)
	ret0, _ := ret[0].(tools.JWT)
	return ret0
}

// Decode indicates an expected call of Decode.
func (mr *MockJWTClientMockRecorder) Decode(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockJWTClient)(nil).Decode), c)
}

// TokenParse mocks base method.
func (m *MockJWTClient) TokenParse(accessToken string) (tools.JWT, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenParse", accessToken)
	ret0, _ := ret[0].(tools.JWT)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TokenParse indicates an expected call of TokenParse.
func (mr *MockJWTClientMockRecorder) TokenParse(accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenParse", reflect.TypeOf((*MockJWTClient)(nil).TokenParse), accessToken)
}
