// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository.go
//
// Generated by this command:
//
//	mockgen -source=./repository.go -destination=../../mocks/bracket/repository_mock.go
//

// Package mock_bracket is a generated GoMock package.
package mock_bracket

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	bracket "github.com/project-ippl-dev/tanding-api/internal/bracket"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// BracketParticipantFetchByEventBracketID mocks base method.
func (m *MockRepository) BracketParticipantFetchByEventBracketID(ctx context.Context, eventBracketID uuid.UUID) ([]bracket.BracketParticipantFetchByEventBracketIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BracketParticipantFetchByEventBracketID", ctx, eventBracketID)
	ret0, _ := ret[0].([]bracket.BracketParticipantFetchByEventBracketIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BracketParticipantFetchByEventBracketID indicates an expected call of BracketParticipantFetchByEventBracketID.
func (mr *MockRepositoryMockRecorder) BracketParticipantFetchByEventBracketID(ctx, eventBracketID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BracketParticipantFetchByEventBracketID", reflect.TypeOf((*MockRepository)(nil).BracketParticipantFetchByEventBracketID), ctx, eventBracketID)
}

// OrderBracketFetchByClassEventID mocks base method.
func (m *MockRepository) OrderBracketFetchByClassEventID(ctx context.Context, classEventID uuid.UUID) ([]bracket.OrderBracketFetchByClassEventIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrderBracketFetchByClassEventID", ctx, classEventID)
	ret0, _ := ret[0].([]bracket.OrderBracketFetchByClassEventIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrderBracketFetchByClassEventID indicates an expected call of OrderBracketFetchByClassEventID.
func (mr *MockRepositoryMockRecorder) OrderBracketFetchByClassEventID(ctx, classEventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderBracketFetchByClassEventID", reflect.TypeOf((*MockRepository)(nil).OrderBracketFetchByClassEventID), ctx, classEventID)
}

// RankFetchByClassEventID mocks base method.
func (m *MockRepository) RankFetchByClassEventID(ctx context.Context, classEventID uuid.UUID) ([]bracket.RankFetchByClassEventIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RankFetchByClassEventID", ctx, classEventID)
	ret0, _ := ret[0].([]bracket.RankFetchByClassEventIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RankFetchByClassEventID indicates an expected call of RankFetchByClassEventID.
func (mr *MockRepositoryMockRecorder) RankFetchByClassEventID(ctx, classEventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RankFetchByClassEventID", reflect.TypeOf((*MockRepository)(nil).RankFetchByClassEventID), ctx, classEventID)
}
