// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase.go
//
// Generated by this command:
//
//	mockgen -source=./usecase.go -destination=../../mocks/bracket/usecase_mock.go
//

// Package mock_bracket is a generated GoMock package.
package mock_bracket

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	bracket "github.com/project-ippl-dev/tanding-api/internal/bracket"
	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// CancelBracket mocks base method.
func (m *MockUsecase) CancelBracket(ctx context.Context, arg bracket.UpdateGenerateParams) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelBracket", ctx, arg)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelBracket indicates an expected call of CancelBracket.
func (mr *MockUsecaseMockRecorder) CancelBracket(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelBracket", reflect.TypeOf((*MockUsecase)(nil).CancelBracket), ctx, arg)
}

// EventTurnLock mocks base method.
func (m *MockUsecase) EventTurnLock(ctx context.Context, eventID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventTurnLock", ctx, eventID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EventTurnLock indicates an expected call of EventTurnLock.
func (mr *MockUsecaseMockRecorder) EventTurnLock(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventTurnLock", reflect.TypeOf((*MockUsecase)(nil).EventTurnLock), ctx, eventID)
}

// FetchOne mocks base method.
func (m *MockUsecase) FetchOne(ctx context.Context, arg bracket.GenerateParams) (bracket.FetchOneResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOne", ctx, arg)
	ret0, _ := ret[0].(bracket.FetchOneResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOne indicates an expected call of FetchOne.
func (mr *MockUsecaseMockRecorder) FetchOne(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOne", reflect.TypeOf((*MockUsecase)(nil).FetchOne), ctx, arg)
}

// OrderLock mocks base method.
func (m *MockUsecase) OrderLock(ctx context.Context, arg bracket.UpdateLockParams) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrderLock", ctx, arg)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrderLock indicates an expected call of OrderLock.
func (mr *MockUsecaseMockRecorder) OrderLock(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderLock", reflect.TypeOf((*MockUsecase)(nil).OrderLock), ctx, arg)
}

// RoundDown mocks base method.
func (m *MockUsecase) RoundDown(ctx context.Context, arg bracket.GenerateParams) (int, bracket.RoundDownResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoundDown", ctx, arg)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(bracket.RoundDownResponse)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RoundDown indicates an expected call of RoundDown.
func (mr *MockUsecaseMockRecorder) RoundDown(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoundDown", reflect.TypeOf((*MockUsecase)(nil).RoundDown), ctx, arg)
}

// Store mocks base method.
func (m *MockUsecase) Store(ctx context.Context, arg bracket.GenerateParams) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, arg)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Store indicates an expected call of Store.
func (mr *MockUsecaseMockRecorder) Store(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockUsecase)(nil).Store), ctx, arg)
}

// UpdateSingleLock mocks base method.
func (m *MockUsecase) UpdateSingleLock(ctx context.Context, arg bracket.UpdateSingleLockParams) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSingleLock", ctx, arg)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSingleLock indicates an expected call of UpdateSingleLock.
func (mr *MockUsecaseMockRecorder) UpdateSingleLock(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSingleLock", reflect.TypeOf((*MockUsecase)(nil).UpdateSingleLock), ctx, arg)
}
