// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase.go
//
// Generated by this command:
//
//	mockgen -source=./usecase.go -destination=../../mocks/classEvent/usecase_mock.go
//

// Package mock_classEvent is a generated GoMock package.
package mock_classEvent

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	classEvent "github.com/project-ippl-dev/tanding-api/internal/classEvent"
	db "github.com/project-ippl-dev/tanding-api/internal/db"
	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// Assign mocks base method.
func (m *MockUsecase) Assign(ctx context.Context, userID string, req classEvent.Request, eventID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Assign", ctx, userID, req, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Assign indicates an expected call of Assign.
func (mr *MockUsecaseMockRecorder) Assign(ctx, userID, req, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assign", reflect.TypeOf((*MockUsecase)(nil).Assign), ctx, userID, req, eventID)
}

// Detach mocks base method.
func (m *MockUsecase) Detach(ctx context.Context, userID string, eventID, classID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detach", ctx, userID, eventID, classID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Detach indicates an expected call of Detach.
func (mr *MockUsecaseMockRecorder) Detach(ctx, userID, eventID, classID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detach", reflect.TypeOf((*MockUsecase)(nil).Detach), ctx, userID, eventID, classID)
}

// FetchAll mocks base method.
func (m *MockUsecase) FetchAll(ctx context.Context, userID string, eventID uuid.UUID) ([]db.ClassEventFetchAllRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAll", ctx, userID, eventID)
	ret0, _ := ret[0].([]db.ClassEventFetchAllRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAll indicates an expected call of FetchAll.
func (mr *MockUsecaseMockRecorder) FetchAll(ctx, userID, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAll", reflect.TypeOf((*MockUsecase)(nil).FetchAll), ctx, userID, eventID)
}

// Update mocks base method.
func (m *MockUsecase) Update(ctx context.Context, req classEvent.UpdateReq, userID string, eventID, classID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req, userID, eventID, classID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUsecaseMockRecorder) Update(ctx, req, userID, eventID, classID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUsecase)(nil).Update), ctx, req, userID, eventID, classID)
}
