// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase.go
//
// Generated by this command:
//
//	mockgen -source=./usecase.go -destination=../../mocks/club/usecase_mock.go
//

// Package mock_club is a generated GoMock package.
package mock_club

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	club "github.com/project-ippl-dev/tanding-api/internal/club"
	db "github.com/project-ippl-dev/tanding-api/internal/db"
	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockUsecase) Delete(ctx context.Context, userID string, clubID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, clubID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUsecaseMockRecorder) Delete(ctx, userID, clubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUsecase)(nil).Delete), ctx, userID, clubID)
}

// FetchInviteApproval mocks base method.
func (m *MockUsecase) FetchInviteApproval(ctx context.Context, limit int32, userID string, ID int64) ([]db.ClubParticipantFetchInviteApprovalRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchInviteApproval", ctx, limit, userID, ID)
	ret0, _ := ret[0].([]db.ClubParticipantFetchInviteApprovalRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchInviteApproval indicates an expected call of FetchInviteApproval.
func (mr *MockUsecaseMockRecorder) FetchInviteApproval(ctx, limit, userID, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchInviteApproval", reflect.TypeOf((*MockUsecase)(nil).FetchInviteApproval), ctx, limit, userID, ID)
}

// FetchJoinApproval mocks base method.
func (m *MockUsecase) FetchJoinApproval(ctx context.Context, limit int32, clubID uuid.UUID, ID int64) ([]db.ClubParticipantFetchJoinApprovalRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchJoinApproval", ctx, limit, clubID, ID)
	ret0, _ := ret[0].([]db.ClubParticipantFetchJoinApprovalRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchJoinApproval indicates an expected call of FetchJoinApproval.
func (mr *MockUsecaseMockRecorder) FetchJoinApproval(ctx, limit, clubID, ID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchJoinApproval", reflect.TypeOf((*MockUsecase)(nil).FetchJoinApproval), ctx, limit, clubID, ID)
}

// Invite mocks base method.
func (m *MockUsecase) Invite(ctx context.Context, req club.ParticipantReq, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invite", ctx, req, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Invite indicates an expected call of Invite.
func (mr *MockUsecaseMockRecorder) Invite(ctx, req, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invite", reflect.TypeOf((*MockUsecase)(nil).Invite), ctx, req, userID)
}

// Join mocks base method.
func (m *MockUsecase) Join(ctx context.Context, req club.JoinParam, userID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Join", ctx, req, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Join indicates an expected call of Join.
func (mr *MockUsecaseMockRecorder) Join(ctx, req, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Join", reflect.TypeOf((*MockUsecase)(nil).Join), ctx, req, userID)
}

// Store mocks base method.
func (m *MockUsecase) Store(ctx context.Context, req club.Request, userID string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, req, userID)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Store indicates an expected call of Store.
func (mr *MockUsecaseMockRecorder) Store(ctx, req, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockUsecase)(nil).Store), ctx, req, userID)
}

// Update mocks base method.
func (m *MockUsecase) Update(ctx context.Context, req club.Request, userID string, clubID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req, userID, clubID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUsecaseMockRecorder) Update(ctx, req, userID, clubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUsecase)(nil).Update), ctx, req, userID, clubID)
}

// UpdateInviteApproval mocks base method.
func (m *MockUsecase) UpdateInviteApproval(ctx context.Context, userID string, req club.UpdateInviteApprovalArgs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInviteApproval", ctx, userID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInviteApproval indicates an expected call of UpdateInviteApproval.
func (mr *MockUsecaseMockRecorder) UpdateInviteApproval(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInviteApproval", reflect.TypeOf((*MockUsecase)(nil).UpdateInviteApproval), ctx, userID, req)
}

// UpdateJoinApproval mocks base method.
func (m *MockUsecase) UpdateJoinApproval(ctx context.Context, userID string, req club.UpdateJoinApprovalArgs) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateJoinApproval", ctx, userID, req)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateJoinApproval indicates an expected call of UpdateJoinApproval.
func (mr *MockUsecaseMockRecorder) UpdateJoinApproval(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJoinApproval", reflect.TypeOf((*MockUsecase)(nil).UpdateJoinApproval), ctx, userID, req)
}
