// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase.go
//
// Generated by this command:
//
//	mockgen -source=./usecase.go -destination=../../mocks/eventRegistration/usecase_mock.go
//

// Package mock_eventRegistration is a generated GoMock package.
package mock_eventRegistration

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	eventRegistration "github.com/project-ippl-dev/tanding-api/internal/eventRegistration"
	tools "github.com/project-ippl-dev/tanding-api/internal/tools"
	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// FetchAll mocks base method.
func (m *MockUsecase) FetchAll(ctx context.Context, args eventRegistration.FetchAllParams, page, pageSize int32) (tools.Pagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAll", ctx, args, page, pageSize)
	ret0, _ := ret[0].(tools.Pagination)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAll indicates an expected call of FetchAll.
func (mr *MockUsecaseMockRecorder) FetchAll(ctx, args, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAll", reflect.TypeOf((*MockUsecase)(nil).FetchAll), ctx, args, page, pageSize)
}

// FetchParticipant mocks base method.
func (m *MockUsecase) FetchParticipant(ctx context.Context, eventID uuid.UUID) ([]eventRegistration.FetchParticipantRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchParticipant", ctx, eventID)
	ret0, _ := ret[0].([]eventRegistration.FetchParticipantRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchParticipant indicates an expected call of FetchParticipant.
func (mr *MockUsecaseMockRecorder) FetchParticipant(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchParticipant", reflect.TypeOf((*MockUsecase)(nil).FetchParticipant), ctx, eventID)
}

// Register mocks base method.
func (m *MockUsecase) Register(ctx context.Context, req eventRegistration.RegistrationRequest) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, req)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockUsecaseMockRecorder) Register(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUsecase)(nil).Register), ctx, req)
}

// SetReject mocks base method.
func (m *MockUsecase) SetReject(ctx context.Context, arg eventRegistration.SetStatusRequest, userID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetReject", ctx, arg, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetReject indicates an expected call of SetReject.
func (mr *MockUsecaseMockRecorder) SetReject(ctx, arg, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetReject", reflect.TypeOf((*MockUsecase)(nil).SetReject), ctx, arg, userID)
}

// Update mocks base method.
func (m *MockUsecase) Update(ctx context.Context, req eventRegistration.UpdateRegistrationRequest, userID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUsecaseMockRecorder) Update(ctx, req, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUsecase)(nil).Update), ctx, req, userID)
}
