// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase.go
//
// Generated by this command:
//
//	mockgen -source=./usecase.go -destination=../../mocks/eventPayment/usecase_mock.go
//

// Package mock_eventPayment is a generated GoMock package.
package mock_eventPayment

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	eventPayment "github.com/project-ippl-dev/tanding-api/internal/eventPayment"
	tools "github.com/project-ippl-dev/tanding-api/internal/tools"
	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// Cart mocks base method.
func (m *MockUsecase) Cart(ctx context.Context, page, pageSize int32, userID string) (tools.Pagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cart", ctx, page, pageSize, userID)
	ret0, _ := ret[0].(tools.Pagination)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cart indicates an expected call of Cart.
func (mr *MockUsecaseMockRecorder) Cart(ctx, page, pageSize, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cart", reflect.TypeOf((*MockUsecase)(nil).Cart), ctx, page, pageSize, userID)
}

// CartDetail mocks base method.
func (m *MockUsecase) CartDetail(ctx context.Context, eventID uuid.UUID, userID string) (eventPayment.CartDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CartDetail", ctx, eventID, userID)
	ret0, _ := ret[0].(eventPayment.CartDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CartDetail indicates an expected call of CartDetail.
func (mr *MockUsecaseMockRecorder) CartDetail(ctx, eventID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CartDetail", reflect.TypeOf((*MockUsecase)(nil).CartDetail), ctx, eventID, userID)
}

// Detail mocks base method.
func (m *MockUsecase) Detail(ctx context.Context, paymentID uuid.UUID) (eventPayment.DetailPaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detail", ctx, paymentID)
	ret0, _ := ret[0].(eventPayment.DetailPaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Detail indicates an expected call of Detail.
func (mr *MockUsecaseMockRecorder) Detail(ctx, paymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detail", reflect.TypeOf((*MockUsecase)(nil).Detail), ctx, paymentID)
}

// FetchAll mocks base method.
func (m *MockUsecase) FetchAll(ctx context.Context, page, pageSize int32, arg eventPayment.FetchAllParams) (tools.Pagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAll", ctx, page, pageSize, arg)
	ret0, _ := ret[0].(tools.Pagination)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAll indicates an expected call of FetchAll.
func (mr *MockUsecaseMockRecorder) FetchAll(ctx, page, pageSize, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAll", reflect.TypeOf((*MockUsecase)(nil).FetchAll), ctx, page, pageSize, arg)
}

// FetchByUserID mocks base method.
func (m *MockUsecase) FetchByUserID(ctx context.Context, page, pageSize int32, arg eventPayment.FetchByUserIDParams, userID string) (int, tools.Pagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByUserID", ctx, page, pageSize, arg, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(tools.Pagination)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FetchByUserID indicates an expected call of FetchByUserID.
func (mr *MockUsecaseMockRecorder) FetchByUserID(ctx, page, pageSize, arg, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByUserID", reflect.TypeOf((*MockUsecase)(nil).FetchByUserID), ctx, page, pageSize, arg, userID)
}

// Store mocks base method.
func (m *MockUsecase) Store(ctx context.Context, req eventPayment.Request, userID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, req, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Store indicates an expected call of Store.
func (mr *MockUsecaseMockRecorder) Store(ctx, req, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockUsecase)(nil).Store), ctx, req, userID)
}

// Summary mocks base method.
func (m *MockUsecase) Summary(ctx context.Context, arg eventPayment.SummaryParams) (eventPayment.SummaryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Summary", ctx, arg)
	ret0, _ := ret[0].(eventPayment.SummaryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Summary indicates an expected call of Summary.
func (mr *MockUsecaseMockRecorder) Summary(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summary", reflect.TypeOf((*MockUsecase)(nil).Summary), ctx, arg)
}

// Update mocks base method.
func (m *MockUsecase) Update(ctx context.Context, arg eventPayment.UpdateParams, userID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, arg, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUsecaseMockRecorder) Update(ctx, arg, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUsecase)(nil).Update), ctx, arg, userID)
}
