// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase.go
//
// Generated by this command:
//
//	mockgen -source=./usecase.go -destination=../../mocks/auth/usecase_mock.go
//

// Package mock_auth is a generated GoMock package.
package mock_auth

import (
	context "context"
	reflect "reflect"

	auth "github.com/project-ippl-dev/tanding-api/internal/auth"
	db "github.com/project-ippl-dev/tanding-api/internal/db"
	tools "github.com/project-ippl-dev/tanding-api/internal/tools"
	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// Binding mocks base method.
func (m *MockUsecase) Binding(ctx context.Context, arg auth.BindingParams) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Binding", ctx, arg)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Binding indicates an expected call of Binding.
func (mr *MockUsecaseMockRecorder) Binding(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Binding", reflect.TypeOf((*MockUsecase)(nil).Binding), ctx, arg)
}

// Callback mocks base method.
func (m *MockUsecase) Callback(ctx context.Context, kind, accessToken string) (int, auth.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Callback", ctx, kind, accessToken)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(auth.LoginResponse)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Callback indicates an expected call of Callback.
func (mr *MockUsecaseMockRecorder) Callback(ctx, kind, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Callback", reflect.TypeOf((*MockUsecase)(nil).Callback), ctx, kind, accessToken)
}

// Check mocks base method.
func (m *MockUsecase) Check(ctx context.Context, kind, username string) (db.UserFetchOneRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, kind, username)
	ret0, _ := ret[0].(db.UserFetchOneRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockUsecaseMockRecorder) Check(ctx, kind, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockUsecase)(nil).Check), ctx, kind, username)
}

// Forgot mocks base method.
func (m *MockUsecase) Forgot(ctx context.Context, username, host, feHost string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Forgot", ctx, username, host, feHost)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Forgot indicates an expected call of Forgot.
func (mr *MockUsecaseMockRecorder) Forgot(ctx, username, host, feHost any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Forgot", reflect.TypeOf((*MockUsecase)(nil).Forgot), ctx, username, host, feHost)
}

// Login mocks base method.
func (m *MockUsecase) Login(ctx context.Context, req auth.LoginReq) (int, auth.LoginResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, req)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(auth.LoginResponse)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Login indicates an expected call of Login.
func (mr *MockUsecaseMockRecorder) Login(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUsecase)(nil).Login), ctx, req)
}

// Register mocks base method.
func (m *MockUsecase) Register(ctx context.Context, req auth.RegisterRequest, host, feHost string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, req, host, feHost)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockUsecaseMockRecorder) Register(ctx, req, host, feHost any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUsecase)(nil).Register), ctx, req, host, feHost)
}

// Resend mocks base method.
func (m *MockUsecase) Resend(ctx context.Context, username, kind string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resend", ctx, username, kind)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resend indicates an expected call of Resend.
func (mr *MockUsecaseMockRecorder) Resend(ctx, username, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resend", reflect.TypeOf((*MockUsecase)(nil).Resend), ctx, username, kind)
}

// Reset mocks base method.
func (m *MockUsecase) Reset(ctx context.Context, req auth.ResetRequest, decoded tools.JWT, token string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reset", ctx, req, decoded, token)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reset indicates an expected call of Reset.
func (mr *MockUsecaseMockRecorder) Reset(ctx, req, decoded, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockUsecase)(nil).Reset), ctx, req, decoded, token)
}

// Verify mocks base method.
func (m *MockUsecase) Verify(ctx context.Context, kind string, decoded tools.JWT, token string) (int, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, kind, decoded, token)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Verify indicates an expected call of Verify.
func (mr *MockUsecaseMockRecorder) Verify(ctx, kind, decoded, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockUsecase)(nil).Verify), ctx, kind, decoded, token)
}
