// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase.go
//
// Generated by this command:
//
//	mockgen -source=./usecase.go -destination=../../mocks/storage/usecase_mock.go
//

// Package mock_storage is a generated GoMock package.
package mock_storage

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"

	storage "github.com/project-ippl-dev/tanding-api/internal/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// Base64ToFile mocks base method.
func (m *MockUsecase) Base64ToFile(data string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Base64ToFile", data)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Base64ToFile indicates an expected call of Base64ToFile.
func (mr *MockUsecaseMockRecorder) Base64ToFile(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Base64ToFile", reflect.TypeOf((*MockUsecase)(nil).Base64ToFile), data)
}

// Base64Upload mocks base method.
func (m *MockUsecase) Base64Upload(req storage.Base64Params) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Base64Upload", req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Base64Upload indicates an expected call of Base64Upload.
func (mr *MockUsecaseMockRecorder) Base64Upload(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Base64Upload", reflect.TypeOf((*MockUsecase)(nil).Base64Upload), req)
}

// Delete mocks base method.
func (m *MockUsecase) Delete(dir, path string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", dir, path)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockUsecaseMockRecorder) Delete(dir, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUsecase)(nil).Delete), dir, path)
}

// ReadMIMEType mocks base method.
func (m *MockUsecase) ReadMIMEType(src multipart.File, fileInformation *storage.FileInformation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadMIMEType", src, fileInformation)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReadMIMEType indicates an expected call of ReadMIMEType.
func (mr *MockUsecaseMockRecorder) ReadMIMEType(src, fileInformation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadMIMEType", reflect.TypeOf((*MockUsecase)(nil).ReadMIMEType), src, fileInformation)
}

// Upload mocks base method.
func (m *MockUsecase) Upload(ctx context.Context, req storage.Params) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockUsecaseMockRecorder) Upload(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockUsecase)(nil).Upload), ctx, req)
}
