// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase.go
//
// Generated by this command:
//
//	mockgen -source=./usecase.go -destination=../../mocks/score/usecase_mock.go
//

// Package mock_score is a generated GoMock package.
package mock_score

import (
	context "context"
	reflect "reflect"

	db "github.com/project-ippl-dev/tanding-api/internal/db"
	score "github.com/project-ippl-dev/tanding-api/internal/score"
	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// FetchOneOrder mocks base method.
func (m *MockUsecase) FetchOneOrder(ctx context.Context, arg score.FetchOneParams) (db.OrderScoreFetchOneByBracketIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOneOrder", ctx, arg)
	ret0, _ := ret[0].(db.OrderScoreFetchOneByBracketIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOneOrder indicates an expected call of FetchOneOrder.
func (mr *MockUsecaseMockRecorder) FetchOneOrder(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOneOrder", reflect.TypeOf((*MockUsecase)(nil).FetchOneOrder), ctx, arg)
}

// FetchOneSingle mocks base method.
func (m *MockUsecase) FetchOneSingle(ctx context.Context, arg score.FetchOneParams) (db.EventScoreFetchOneByBracketIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOneSingle", ctx, arg)
	ret0, _ := ret[0].(db.EventScoreFetchOneByBracketIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOneSingle indicates an expected call of FetchOneSingle.
func (mr *MockUsecaseMockRecorder) FetchOneSingle(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOneSingle", reflect.TypeOf((*MockUsecase)(nil).FetchOneSingle), ctx, arg)
}

// Lock mocks base method.
func (m *MockUsecase) Lock(ctx context.Context, arg score.LockParams) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lock", ctx, arg)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lock indicates an expected call of Lock.
func (mr *MockUsecaseMockRecorder) Lock(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lock", reflect.TypeOf((*MockUsecase)(nil).Lock), ctx, arg)
}

// StoreOrUpdateOrder mocks base method.
func (m *MockUsecase) StoreOrUpdateOrder(ctx context.Context, arg score.OrderStoreOrUpdateParams) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreOrUpdateOrder", ctx, arg)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreOrUpdateOrder indicates an expected call of StoreOrUpdateOrder.
func (mr *MockUsecaseMockRecorder) StoreOrUpdateOrder(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreOrUpdateOrder", reflect.TypeOf((*MockUsecase)(nil).StoreOrUpdateOrder), ctx, arg)
}

// StoreOrUpdateSingle mocks base method.
func (m *MockUsecase) StoreOrUpdateSingle(ctx context.Context, arg score.SingleStoreOrUpdateParams) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreOrUpdateSingle", ctx, arg)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreOrUpdateSingle indicates an expected call of StoreOrUpdateSingle.
func (mr *MockUsecaseMockRecorder) StoreOrUpdateSingle(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreOrUpdateSingle", reflect.TypeOf((*MockUsecase)(nil).StoreOrUpdateSingle), ctx, arg)
}
