// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: accomplishment.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const accomplishmentCheckOne = `-- name: AccomplishmentCheckOne :one
SELECT id FROM accomplishments WHERE id = $1 AND user_id = $2 LIMIT 1
`

type AccomplishmentCheckOneParams struct {
	ID     int64     `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) AccomplishmentCheckOne(ctx context.Context, arg AccomplishmentCheckOneParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, accomplishmentCheckOne, arg.ID, arg.UserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const accomplishmentCountAll = `-- name: AccomplishmentCountAll :one
SELECT COUNT(id) FROM accomplishments WHERE user_id = $1 LIMIT 1
`

func (q *Queries) AccomplishmentCountAll(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, accomplishmentCountAll, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const accomplishmentCreate = `-- name: AccomplishmentCreate :exec
INSERT INTO accomplishments(user_id, title, level, ranking, category, sport, description, file_url, month, year, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW())
`

type AccomplishmentCreateParams struct {
	UserID      uuid.UUID           `json:"user_id"`
	Title       string              `json:"title"`
	Level       AccomplishmentLevel `json:"level"`
	Ranking     string              `json:"ranking"`
	Category    string              `json:"category"`
	Sport       string              `json:"sport"`
	Description sql.NullString      `json:"description"`
	FileUrl     string              `json:"file_url"`
	Month       int16               `json:"month"`
	Year        int16               `json:"year"`
}

func (q *Queries) AccomplishmentCreate(ctx context.Context, arg AccomplishmentCreateParams) error {
	_, err := q.db.ExecContext(ctx, accomplishmentCreate,
		arg.UserID,
		arg.Title,
		arg.Level,
		arg.Ranking,
		arg.Category,
		arg.Sport,
		arg.Description,
		arg.FileUrl,
		arg.Month,
		arg.Year,
	)
	return err
}

const accomplishmentDelete = `-- name: AccomplishmentDelete :exec
DELETE FROM accomplishments WHERE id = $1
`

func (q *Queries) AccomplishmentDelete(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, accomplishmentDelete, id)
	return err
}

const accomplishmentFetchAll = `-- name: AccomplishmentFetchAll :many
SELECT id, user_id, title, level, ranking, category, sport, description, file_url, month, year FROM accomplishments
WHERE user_id = $1 ORDER BY year DESC, month DESC LIMIT $2 OFFSET $3
`

type AccomplishmentFetchAllParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type AccomplishmentFetchAllRow struct {
	ID          int64               `json:"id"`
	UserID      uuid.UUID           `json:"user_id"`
	Title       string              `json:"title"`
	Level       AccomplishmentLevel `json:"level"`
	Ranking     string              `json:"ranking"`
	Category    string              `json:"category"`
	Sport       string              `json:"sport"`
	Description sql.NullString      `json:"description"`
	FileUrl     string              `json:"file_url"`
	Month       int16               `json:"month"`
	Year        int16               `json:"year"`
}

func (q *Queries) AccomplishmentFetchAll(ctx context.Context, arg AccomplishmentFetchAllParams) ([]AccomplishmentFetchAllRow, error) {
	rows, err := q.db.QueryContext(ctx, accomplishmentFetchAll, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccomplishmentFetchAllRow{}
	for rows.Next() {
		var i AccomplishmentFetchAllRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Level,
			&i.Ranking,
			&i.Category,
			&i.Sport,
			&i.Description,
			&i.FileUrl,
			&i.Month,
			&i.Year,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accomplishmentUpdate = `-- name: AccomplishmentUpdate :exec
UPDATE accomplishments SET title = $1,
                           level = $2,
                           ranking = $3,
                           category = $4,
                           sport = $5,
                           description = $6,
                           file_url = $7,
                           month = $8,
                           year = $9,
                           updated_at = NOW()
WHERE id = $10
`

type AccomplishmentUpdateParams struct {
	Title       string              `json:"title"`
	Level       AccomplishmentLevel `json:"level"`
	Ranking     string              `json:"ranking"`
	Category    string              `json:"category"`
	Sport       string              `json:"sport"`
	Description sql.NullString      `json:"description"`
	FileUrl     string              `json:"file_url"`
	Month       int16               `json:"month"`
	Year        int16               `json:"year"`
	ID          int64               `json:"id"`
}

func (q *Queries) AccomplishmentUpdate(ctx context.Context, arg AccomplishmentUpdateParams) error {
	_, err := q.db.ExecContext(ctx, accomplishmentUpdate,
		arg.Title,
		arg.Level,
		arg.Ranking,
		arg.Category,
		arg.Sport,
		arg.Description,
		arg.FileUrl,
		arg.Month,
		arg.Year,
		arg.ID,
	)
	return err
}
