// Code generated by sqlc. DO NOT EDIT.
// source: account.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const accountCreate = `-- name: AccountCreate :one
INSERT INTO accounts(username, password, type, user_id, status, updated_at) VALUES ($1, $2, $3, $4, $5, NOW())
RETURNING id
`

type AccountCreateParams struct {
	Username string      `json:"username"`
	Password string      `json:"password"`
	Type     AccountType `json:"type"`
	UserID   uuid.UUID   `json:"user_id"`
	Status   bool        `json:"status"`
}

func (q *Queries) AccountCreate(ctx context.Context, arg AccountCreateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, accountCreate,
		arg.Username,
		arg.Password,
		arg.Type,
		arg.UserID,
		arg.Status,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const accountFetchEmailByID = `-- name: AccountFetchEmailByID :one
SELECT username FROM accounts INNER JOIN users ON users.id = accounts.user_id
WHERE accounts.id = $1 AND accounts.type = $2 AND users.status = '1' LIMIT 1
`

type AccountFetchEmailByIDParams struct {
	ID   int64       `json:"id"`
	Type AccountType `json:"type"`
}

func (q *Queries) AccountFetchEmailByID(ctx context.Context, arg AccountFetchEmailByIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, accountFetchEmailByID, arg.ID, arg.Type)
	var username string
	err := row.Scan(&username)
	return username, err
}

const accountFetchOneByEmail = `-- name: AccountFetchOneByEmail :one
SELECT accounts.id, accounts.username, accounts.password, accounts.user_id,
       users.role, users.photo, users.name, users.can_participate
FROM accounts INNER JOIN users ON users.id = accounts.user_id
WHERE username = $1 AND type = $2 AND users.status = '1' LIMIT 1
`

type AccountFetchOneByEmailParams struct {
	Username string      `json:"username"`
	Type     AccountType `json:"type"`
}

type AccountFetchOneByEmailRow struct {
	ID             int64     `json:"id"`
	Username       string    `json:"username"`
	Password       string    `json:"password"`
	UserID         uuid.UUID `json:"user_id"`
	Role           Role      `json:"role"`
	Photo          string    `json:"photo"`
	Name           string    `json:"name"`
	CanParticipate bool      `json:"can_participate"`
}

func (q *Queries) AccountFetchOneByEmail(ctx context.Context, arg AccountFetchOneByEmailParams) (AccountFetchOneByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, accountFetchOneByEmail, arg.Username, arg.Type)
	var i AccountFetchOneByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.UserID,
		&i.Role,
		&i.Photo,
		&i.Name,
		&i.CanParticipate,
	)
	return i, err
}

const accountFetchUserIDByUsername = `-- name: AccountFetchUserIDByUsername :one
SELECT accounts.user_id FROM accounts INNER JOIN users ON users.id = accounts.user_id
WHERE accounts.username = $1 AND accounts.type = $2 AND users.status = '1' LIMIT 1
`

type AccountFetchUserIDByUsernameParams struct {
	Username string      `json:"username"`
	Type     AccountType `json:"type"`
}

func (q *Queries) AccountFetchUserIDByUsername(ctx context.Context, arg AccountFetchUserIDByUsernameParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, accountFetchUserIDByUsername, arg.Username, arg.Type)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const accountUpdatePassword = `-- name: AccountUpdatePassword :exec
UPDATE accounts SET password = $1,
                    updated_at = NOW()
WHERE id = $2
`

type AccountUpdatePasswordParams struct {
	Password string `json:"password"`
	ID       int64  `json:"id"`
}

func (q *Queries) AccountUpdatePassword(ctx context.Context, arg AccountUpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, accountUpdatePassword, arg.Password, arg.ID)
	return err
}

const accountUpdateStatusByID = `-- name: AccountUpdateStatusByID :exec
UPDATE accounts SET status = true,
                    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) AccountUpdateStatusByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, accountUpdateStatusByID, id)
	return err
}
