// Code generated by sqlc. DO NOT EDIT.
// source: bracketParticipant.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const bracketParticipantCheckOneByEventBracketIDAndType = `-- name: BracketParticipantCheckOneByEventBracketIDAndType :one
SELECT id FROM bracket_participants WHERE event_bracket_id = $1 AND type = $2
`

type BracketParticipantCheckOneByEventBracketIDAndTypeParams struct {
	EventBracketID uuid.UUID       `json:"event_bracket_id"`
	Type           ParticipantType `json:"type"`
}

func (q *Queries) BracketParticipantCheckOneByEventBracketIDAndType(ctx context.Context, arg BracketParticipantCheckOneByEventBracketIDAndTypeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, bracketParticipantCheckOneByEventBracketIDAndType, arg.EventBracketID, arg.Type)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const bracketParticipantCreate = `-- name: BracketParticipantCreate :exec
INSERT INTO bracket_participants(event_registration_id, event_bracket_id, type, is_bye, updated_at)
VALUES ($1, $2, $3, $4, NOW())
`

type BracketParticipantCreateParams struct {
	EventRegistrationID uuid.UUID       `json:"event_registration_id"`
	EventBracketID      uuid.UUID       `json:"event_bracket_id"`
	Type                ParticipantType `json:"type"`
	IsBye               bool            `json:"is_bye"`
}

func (q *Queries) BracketParticipantCreate(ctx context.Context, arg BracketParticipantCreateParams) error {
	_, err := q.db.ExecContext(ctx, bracketParticipantCreate,
		arg.EventRegistrationID,
		arg.EventBracketID,
		arg.Type,
		arg.IsBye,
	)
	return err
}

const bracketParticipantFetchByBracketIDAndType = `-- name: BracketParticipantFetchByBracketIDAndType :one
SELECT bp.event_registration_id, er.club_id FROM bracket_participants as bp
INNER JOIN event_registrations as er ON er.id = bp.event_registration_id
WHERE bp.event_bracket_id = $1 AND bp.type = $2
`

type BracketParticipantFetchByBracketIDAndTypeParams struct {
	EventBracketID uuid.UUID       `json:"event_bracket_id"`
	Type           ParticipantType `json:"type"`
}

type BracketParticipantFetchByBracketIDAndTypeRow struct {
	EventRegistrationID uuid.UUID `json:"event_registration_id"`
	ClubID              uuid.UUID `json:"club_id"`
}

func (q *Queries) BracketParticipantFetchByBracketIDAndType(ctx context.Context, arg BracketParticipantFetchByBracketIDAndTypeParams) (BracketParticipantFetchByBracketIDAndTypeRow, error) {
	row := q.db.QueryRowContext(ctx, bracketParticipantFetchByBracketIDAndType, arg.EventBracketID, arg.Type)
	var i BracketParticipantFetchByBracketIDAndTypeRow
	err := row.Scan(&i.EventRegistrationID, &i.ClubID)
	return i, err
}

const bracketParticipantFetchByEventBracketID = `-- name: BracketParticipantFetchByEventBracketID :many
SELECT bp.id, er.club_id, c.name as club_name, bp.type, bp.event_registration_id FROM bracket_participants as bp
INNER JOIN event_registrations as er ON er.id = bp.event_registration_id
INNER JOIN clubs as c ON c.id  = er.club_id
WHERE bp.event_bracket_id = $1
ORDER BY CASE bp.type
             WHEN 'home' THEN 1
             WHEN 'away' THEN 2
             END
`

type BracketParticipantFetchByEventBracketIDRow struct {
	ID                  int64           `json:"id"`
	ClubID              uuid.UUID       `json:"club_id"`
	ClubName            string          `json:"club_name"`
	Type                ParticipantType `json:"type"`
	EventRegistrationID uuid.UUID       `json:"event_registration_id"`
}

func (q *Queries) BracketParticipantFetchByEventBracketID(ctx context.Context, eventBracketID uuid.UUID) ([]BracketParticipantFetchByEventBracketIDRow, error) {
	rows, err := q.db.QueryContext(ctx, bracketParticipantFetchByEventBracketID, eventBracketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BracketParticipantFetchByEventBracketIDRow{}
	for rows.Next() {
		var i BracketParticipantFetchByEventBracketIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.ClubName,
			&i.Type,
			&i.EventRegistrationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bracketParticipantUpdate = `-- name: BracketParticipantUpdate :exec
UPDATE bracket_participants SET event_registration_id = $1,
                                updated_at = NOW()
WHERE id = $2
`

type BracketParticipantUpdateParams struct {
	EventRegistrationID uuid.UUID `json:"event_registration_id"`
	ID                  int64     `json:"id"`
}

func (q *Queries) BracketParticipantUpdate(ctx context.Context, arg BracketParticipantUpdateParams) error {
	_, err := q.db.ExecContext(ctx, bracketParticipantUpdate, arg.EventRegistrationID, arg.ID)
	return err
}

const bracketParticipantUpdateByParticipantType = `-- name: BracketParticipantUpdateByParticipantType :exec
UPDATE bracket_participants SET event_registration_id = $1,
                                updated_at = NOW()
WHERE event_bracket_id = $2 AND type = $3
`

type BracketParticipantUpdateByParticipantTypeParams struct {
	EventRegistrationID uuid.UUID       `json:"event_registration_id"`
	EventBracketID      uuid.UUID       `json:"event_bracket_id"`
	Type                ParticipantType `json:"type"`
}

func (q *Queries) BracketParticipantUpdateByParticipantType(ctx context.Context, arg BracketParticipantUpdateByParticipantTypeParams) error {
	_, err := q.db.ExecContext(ctx, bracketParticipantUpdateByParticipantType, arg.EventRegistrationID, arg.EventBracketID, arg.Type)
	return err
}
