// Code generated by sqlc. DO NOT EDIT.
// source: certificate.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const certificateCountAll = `-- name: CertificateCountAll :one
SELECT COUNT(id) FROM certificates
`

func (q *Queries) CertificateCountAll(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, certificateCountAll)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const certificateCountAllByUserID = `-- name: CertificateCountAllByUserID :one
SELECT COUNT(id) FROM certificates WHERE user_id = $1
`

func (q *Queries) CertificateCountAllByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, certificateCountAllByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const certificateCreate = `-- name: CertificateCreate :exec
INSERT INTO certificates(id, user_id, event_id, reward_as, class_event_id, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
`

type CertificateCreateParams struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	EventID      uuid.UUID `json:"event_id"`
	RewardAs     string    `json:"reward_as"`
	ClassEventID uuid.UUID `json:"class_event_id"`
}

func (q *Queries) CertificateCreate(ctx context.Context, arg CertificateCreateParams) error {
	_, err := q.db.ExecContext(ctx, certificateCreate,
		arg.ID,
		arg.UserID,
		arg.EventID,
		arg.RewardAs,
		arg.ClassEventID,
	)
	return err
}

const certificateFetchAllByUserID = `-- name: CertificateFetchAllByUserID :many
SELECT c.id, u.name, e.name as event_name, e.thumbnail, c.reward_as, c.created_at FROM certificates as c
INNER JOIN users as u ON u.id = c.user_id
INNER JOIN events as e ON e.id = c.event_id
WHERE c.user_id = $1
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type CertificateFetchAllByUserIDParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type CertificateFetchAllByUserIDRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	EventName string    `json:"event_name"`
	Thumbnail string    `json:"thumbnail"`
	RewardAs  string    `json:"reward_as"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CertificateFetchAllByUserID(ctx context.Context, arg CertificateFetchAllByUserIDParams) ([]CertificateFetchAllByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, certificateFetchAllByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CertificateFetchAllByUserIDRow{}
	for rows.Next() {
		var i CertificateFetchAllByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EventName,
			&i.Thumbnail,
			&i.RewardAs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const certificateFetchOne = `-- name: CertificateFetchOne :one
SELECT c.id, u.name, c.event_id, c.user_id, e.name as event_name, c.reward_as, c.created_at FROM certificates as c
INNER JOIN users as u ON u.id = c.user_id
INNER JOIN events as e ON e.id = c.event_id
WHERE c.id = $1
`

type CertificateFetchOneRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	EventID   uuid.UUID `json:"event_id"`
	UserID    uuid.UUID `json:"user_id"`
	EventName string    `json:"event_name"`
	RewardAs  string    `json:"reward_as"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CertificateFetchOne(ctx context.Context, id uuid.UUID) (CertificateFetchOneRow, error) {
	row := q.db.QueryRowContext(ctx, certificateFetchOne, id)
	var i CertificateFetchOneRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EventID,
		&i.UserID,
		&i.EventName,
		&i.RewardAs,
		&i.CreatedAt,
	)
	return i, err
}
