// Code generated by sqlc. DO NOT EDIT.
// source: class.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const classCheckOne = `-- name: ClassCheckOne :one
SELECT id, name, type, match_type FROM classes WHERE id = $1 LIMIT 1
`

type ClassCheckOneRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Type      ClassType `json:"type"`
	MatchType MatchType `json:"match_type"`
}

func (q *Queries) ClassCheckOne(ctx context.Context, id uuid.UUID) (ClassCheckOneRow, error) {
	row := q.db.QueryRowContext(ctx, classCheckOne, id)
	var i ClassCheckOneRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.MatchType,
	)
	return i, err
}

const classCountAll = `-- name: ClassCountAll :one
SELECT COUNT(id) FROM classes LIMIT 1
`

func (q *Queries) ClassCountAll(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, classCountAll)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const classCountBySportID = `-- name: ClassCountBySportID :one
SELECT COUNT(id) FROM classes WHERE sport_id = $1 LIMIT 1
`

func (q *Queries) ClassCountBySportID(ctx context.Context, sportID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, classCountBySportID, sportID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const classCreate = `-- name: ClassCreate :exec
INSERT INTO classes(sport_id, name, class_competition_rule_id, type, match_type, updated_at)
VALUES($1, $2, $3, $4, $5, NOW())
`

type ClassCreateParams struct {
	SportID                uuid.UUID `json:"sport_id"`
	Name                   string    `json:"name"`
	ClassCompetitionRuleID int64     `json:"class_competition_rule_id"`
	Type                   ClassType `json:"type"`
	MatchType              MatchType `json:"match_type"`
}

func (q *Queries) ClassCreate(ctx context.Context, arg ClassCreateParams) error {
	_, err := q.db.ExecContext(ctx, classCreate,
		arg.SportID,
		arg.Name,
		arg.ClassCompetitionRuleID,
		arg.Type,
		arg.MatchType,
	)
	return err
}

const classDelete = `-- name: ClassDelete :exec
DELETE FROM classes WHERE id = $1
`

func (q *Queries) ClassDelete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, classDelete, id)
	return err
}

const classFetchAll = `-- name: ClassFetchAll :many
SELECT c.id, c.name, c.class_competition_rule_id, ccr.name as class_rule_name, c.type, c.sport_id, c.match_type, s.name as sport_name FROM classes as c
INNER JOIN sports as s ON s.id = c.sport_id
INNER JOIN class_competition_rules as ccr ON ccr.id = c.class_competition_rule_id
ORDER BY c.created_at DESC LIMIT $1 OFFSET $2
`

type ClassFetchAllParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ClassFetchAllRow struct {
	ID                     uuid.UUID `json:"id"`
	Name                   string    `json:"name"`
	ClassCompetitionRuleID int64     `json:"class_competition_rule_id"`
	ClassRuleName          string    `json:"class_rule_name"`
	Type                   ClassType `json:"type"`
	SportID                uuid.UUID `json:"sport_id"`
	MatchType              MatchType `json:"match_type"`
	SportName              string    `json:"sport_name"`
}

func (q *Queries) ClassFetchAll(ctx context.Context, arg ClassFetchAllParams) ([]ClassFetchAllRow, error) {
	rows, err := q.db.QueryContext(ctx, classFetchAll, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClassFetchAllRow{}
	for rows.Next() {
		var i ClassFetchAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ClassCompetitionRuleID,
			&i.ClassRuleName,
			&i.Type,
			&i.SportID,
			&i.MatchType,
			&i.SportName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const classFetchBySportID = `-- name: ClassFetchBySportID :many
SELECT c.id, c.name, c.class_competition_rule_id, ccr.name as class_rule_name, c.type, c.sport_id, c.match_type, s.name as sport_name FROM classes as c
INNER JOIN sports as s ON s.id = c.sport_id
INNER JOIN class_competition_rules as ccr ON ccr.id = c.class_competition_rule_id
WHERE c.sport_id = $1 ORDER BY c.created_at DESC LIMIT $2 OFFSET $3
`

type ClassFetchBySportIDParams struct {
	SportID uuid.UUID `json:"sport_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

type ClassFetchBySportIDRow struct {
	ID                     uuid.UUID `json:"id"`
	Name                   string    `json:"name"`
	ClassCompetitionRuleID int64     `json:"class_competition_rule_id"`
	ClassRuleName          string    `json:"class_rule_name"`
	Type                   ClassType `json:"type"`
	SportID                uuid.UUID `json:"sport_id"`
	MatchType              MatchType `json:"match_type"`
	SportName              string    `json:"sport_name"`
}

func (q *Queries) ClassFetchBySportID(ctx context.Context, arg ClassFetchBySportIDParams) ([]ClassFetchBySportIDRow, error) {
	rows, err := q.db.QueryContext(ctx, classFetchBySportID, arg.SportID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClassFetchBySportIDRow{}
	for rows.Next() {
		var i ClassFetchBySportIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ClassCompetitionRuleID,
			&i.ClassRuleName,
			&i.Type,
			&i.SportID,
			&i.MatchType,
			&i.SportName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const classUpdate = `-- name: ClassUpdate :exec
UPDATE classes SET sport_id = $1,
                   name = $2,
                   class_competition_rule_id = $3,
                   type = $4,
                   match_type = $5,
                   updated_at = NOW()
WHERE id = $6
`

type ClassUpdateParams struct {
	SportID                uuid.UUID `json:"sport_id"`
	Name                   string    `json:"name"`
	ClassCompetitionRuleID int64     `json:"class_competition_rule_id"`
	Type                   ClassType `json:"type"`
	MatchType              MatchType `json:"match_type"`
	ID                     uuid.UUID `json:"id"`
}

func (q *Queries) ClassUpdate(ctx context.Context, arg ClassUpdateParams) error {
	_, err := q.db.ExecContext(ctx, classUpdate,
		arg.SportID,
		arg.Name,
		arg.ClassCompetitionRuleID,
		arg.Type,
		arg.MatchType,
		arg.ID,
	)
	return err
}
