// Code generated by sqlc. DO NOT EDIT.
// source: classCompetitionRule.sql

package db

import (
	"context"
)

const classRuleCountAll = `-- name: ClassRuleCountAll :one
SELECT COUNT(id) FROM class_competition_rules
`

func (q *Queries) ClassRuleCountAll(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, classRuleCountAll)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const classRuleCreate = `-- name: ClassRuleCreate :exec
INSERT INTO class_competition_rules(name, male, female, total, updated_at) VALUES ($1, $2, $3, $4, NOW())
`

type ClassRuleCreateParams struct {
	Name   string `json:"name"`
	Male   int16  `json:"male"`
	Female int16  `json:"female"`
	Total  int16  `json:"total"`
}

func (q *Queries) ClassRuleCreate(ctx context.Context, arg ClassRuleCreateParams) error {
	_, err := q.db.ExecContext(ctx, classRuleCreate,
		arg.Name,
		arg.Male,
		arg.Female,
		arg.Total,
	)
	return err
}

const classRuleDelete = `-- name: ClassRuleDelete :exec
DELETE FROM class_competition_rules WHERE id = $1
`

func (q *Queries) ClassRuleDelete(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, classRuleDelete, id)
	return err
}

const classRuleFetchAll = `-- name: ClassRuleFetchAll :many
SELECT id, name, male, female, total FROM class_competition_rules ORDER BY name LIMIT $1 OFFSET $2
`

type ClassRuleFetchAllParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ClassRuleFetchAllRow struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	Male   int16  `json:"male"`
	Female int16  `json:"female"`
	Total  int16  `json:"total"`
}

func (q *Queries) ClassRuleFetchAll(ctx context.Context, arg ClassRuleFetchAllParams) ([]ClassRuleFetchAllRow, error) {
	rows, err := q.db.QueryContext(ctx, classRuleFetchAll, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClassRuleFetchAllRow{}
	for rows.Next() {
		var i ClassRuleFetchAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Male,
			&i.Female,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const classRuleFetchOne = `-- name: ClassRuleFetchOne :one
SELECT id, name, male, female, total FROM class_competition_rules WHERE id = $1 LIMIT 1
`

type ClassRuleFetchOneRow struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	Male   int16  `json:"male"`
	Female int16  `json:"female"`
	Total  int16  `json:"total"`
}

func (q *Queries) ClassRuleFetchOne(ctx context.Context, id int64) (ClassRuleFetchOneRow, error) {
	row := q.db.QueryRowContext(ctx, classRuleFetchOne, id)
	var i ClassRuleFetchOneRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Male,
		&i.Female,
		&i.Total,
	)
	return i, err
}

const classRuleUpdate = `-- name: ClassRuleUpdate :exec
UPDATE class_competition_rules SET name = $1,
                                   male = $2,
                                   female = $3,
                                   total = $4,
                                   updated_at = NOW()
WHERE id = $5
`

type ClassRuleUpdateParams struct {
	Name   string `json:"name"`
	Male   int16  `json:"male"`
	Female int16  `json:"female"`
	Total  int16  `json:"total"`
	ID     int64  `json:"id"`
}

func (q *Queries) ClassRuleUpdate(ctx context.Context, arg ClassRuleUpdateParams) error {
	_, err := q.db.ExecContext(ctx, classRuleUpdate,
		arg.Name,
		arg.Male,
		arg.Female,
		arg.Total,
		arg.ID,
	)
	return err
}
