// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: classEvent.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const classEventAssign = `-- name: ClassEventAssign :exec
INSERT INTO class_events (class_id, event_id, price, updated_at) VALUES ($1, $2, $3, NOW())
`

type ClassEventAssignParams struct {
	ClassID uuid.UUID `json:"class_id"`
	EventID uuid.UUID `json:"event_id"`
	Price   int32     `json:"price"`
}

func (q *Queries) ClassEventAssign(ctx context.Context, arg ClassEventAssignParams) error {
	_, err := q.db.ExecContext(ctx, classEventAssign, arg.ClassID, arg.EventID, arg.Price)
	return err
}

const classEventCheckOne = `-- name: ClassEventCheckOne :one
SELECT ce.id FROM class_events as ce INNER JOIN events as e ON e.id = ce.event_id
WHERE ce.id = $1 AND ce.event_id = $2 AND e.user_id = $3 LIMIT 1
`

type ClassEventCheckOneParams struct {
	ID      uuid.UUID `json:"id"`
	EventID uuid.UUID `json:"event_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) ClassEventCheckOne(ctx context.Context, arg ClassEventCheckOneParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, classEventCheckOne, arg.ID, arg.EventID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const classEventDetach = `-- name: ClassEventDetach :exec
DELETE FROM class_events WHERE id = $1 AND event_id = $2
`

type ClassEventDetachParams struct {
	ID      uuid.UUID `json:"id"`
	EventID uuid.UUID `json:"event_id"`
}

func (q *Queries) ClassEventDetach(ctx context.Context, arg ClassEventDetachParams) error {
	_, err := q.db.ExecContext(ctx, classEventDetach, arg.ID, arg.EventID)
	return err
}

const classEventFetchAll = `-- name: ClassEventFetchAll :many
SELECT ce.id, c.name as class_name FROM class_events as ce
    INNER JOIN classes as c ON c.id = ce.class_id
    INNER JOIN events as e ON e.id = ce.event_id
WHERE e.id = $1 AND e.user_id = $2 ORDER BY ce.created_at DESC
`

type ClassEventFetchAllParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type ClassEventFetchAllRow struct {
	ID        uuid.UUID `json:"id"`
	ClassName string    `json:"class_name"`
}

func (q *Queries) ClassEventFetchAll(ctx context.Context, arg ClassEventFetchAllParams) ([]ClassEventFetchAllRow, error) {
	rows, err := q.db.QueryContext(ctx, classEventFetchAll, arg.ID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClassEventFetchAllRow{}
	for rows.Next() {
		var i ClassEventFetchAllRow
		if err := rows.Scan(&i.ID, &i.ClassName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const classEventFetchAndGroupByEventID = `-- name: ClassEventFetchAndGroupByEventID :many
SELECT ce.id, c.name, ce.match_index, count(eb.id) as total_match,
       count(eb.status) FILTER (WHERE eb.status = 'bye') AS total_bye
FROM class_events as ce
INNER JOIN classes as c ON c.id = ce.class_id
INNER JOIN event_brackets as eb ON eb.class_event_id = ce.id
WHERE ce.event_id = $1
GROUP BY ce.id, c.name ORDER BY ce.match_index DESC, total_match DESC, total_bye
`

type ClassEventFetchAndGroupByEventIDRow struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	MatchIndex int16     `json:"match_index"`
	TotalMatch int64     `json:"total_match"`
	TotalBye   int64     `json:"total_bye"`
}

func (q *Queries) ClassEventFetchAndGroupByEventID(ctx context.Context, eventID uuid.UUID) ([]ClassEventFetchAndGroupByEventIDRow, error) {
	rows, err := q.db.QueryContext(ctx, classEventFetchAndGroupByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClassEventFetchAndGroupByEventIDRow{}
	for rows.Next() {
		var i ClassEventFetchAndGroupByEventIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MatchIndex,
			&i.TotalMatch,
			&i.TotalBye,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const classEventFetchByEventID = `-- name: ClassEventFetchByEventID :many
SELECT ce.id, ce.class_id, c.name as class_name, ce.price, c.match_type, cpr.name as class_rule_name,
       cpr.male as class_rule_male, cpr.female as class_rule_female, cpr.total as class_rule_total
FROM class_events as ce
INNER JOIN classes as c ON c.id = ce.class_id
INNER JOIN class_competition_rules as cpr ON cpr.id = c.class_competition_rule_id
INNER JOIN events as e ON e.id = ce.event_id
WHERE e.id = $1 ORDER BY ce.created_at DESC
`

type ClassEventFetchByEventIDRow struct {
	ID              uuid.UUID `json:"id"`
	ClassID         uuid.UUID `json:"class_id"`
	ClassName       string    `json:"class_name"`
	Price           int32     `json:"price"`
	MatchType       MatchType `json:"match_type"`
	ClassRuleName   string    `json:"class_rule_name"`
	ClassRuleMale   int16     `json:"class_rule_male"`
	ClassRuleFemale int16     `json:"class_rule_female"`
	ClassRuleTotal  int16     `json:"class_rule_total"`
}

func (q *Queries) ClassEventFetchByEventID(ctx context.Context, id uuid.UUID) ([]ClassEventFetchByEventIDRow, error) {
	rows, err := q.db.QueryContext(ctx, classEventFetchByEventID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClassEventFetchByEventIDRow{}
	for rows.Next() {
		var i ClassEventFetchByEventIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ClassID,
			&i.ClassName,
			&i.Price,
			&i.MatchType,
			&i.ClassRuleName,
			&i.ClassRuleMale,
			&i.ClassRuleFemale,
			&i.ClassRuleTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const classEventFetchByEventIDAndScoreLockTrue = `-- name: ClassEventFetchByEventIDAndScoreLockTrue :many
SELECT ce.id, ce.class_id, c.name as class_name, ce.price, c.match_type, cpr.name as class_rule_name,
       cpr.male as class_rule_male, cpr.female as class_rule_female, cpr.total as class_rule_total, ce.match_index
FROM class_events as ce
         INNER JOIN classes as c ON c.id = ce.class_id
         INNER JOIN class_competition_rules as cpr ON cpr.id = c.class_competition_rule_id
         INNER JOIN events as e ON e.id = ce.event_id
WHERE e.id = $1 AND ce.score_lock = TRUE ORDER BY ce.created_at DESC
`

type ClassEventFetchByEventIDAndScoreLockTrueRow struct {
	ID              uuid.UUID `json:"id"`
	ClassID         uuid.UUID `json:"class_id"`
	ClassName       string    `json:"class_name"`
	Price           int32     `json:"price"`
	MatchType       MatchType `json:"match_type"`
	ClassRuleName   string    `json:"class_rule_name"`
	ClassRuleMale   int16     `json:"class_rule_male"`
	ClassRuleFemale int16     `json:"class_rule_female"`
	ClassRuleTotal  int16     `json:"class_rule_total"`
	MatchIndex      int16     `json:"match_index"`
}

func (q *Queries) ClassEventFetchByEventIDAndScoreLockTrue(ctx context.Context, id uuid.UUID) ([]ClassEventFetchByEventIDAndScoreLockTrueRow, error) {
	rows, err := q.db.QueryContext(ctx, classEventFetchByEventIDAndScoreLockTrue, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClassEventFetchByEventIDAndScoreLockTrueRow{}
	for rows.Next() {
		var i ClassEventFetchByEventIDAndScoreLockTrueRow
		if err := rows.Scan(
			&i.ID,
			&i.ClassID,
			&i.ClassName,
			&i.Price,
			&i.MatchType,
			&i.ClassRuleName,
			&i.ClassRuleMale,
			&i.ClassRuleFemale,
			&i.ClassRuleTotal,
			&i.MatchIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const classEventFetchByPaymentID = `-- name: ClassEventFetchByPaymentID :many
SELECT DISTINCT ce.id, ce.price, c.name FROM class_events as ce
INNER JOIN classes as c ON c.id = ce.class_id
INNER JOIN event_registrations as er ON er.class_event_id = ce.id
INNER JOIN event_payment_receipts as epr ON epr.id = er.event_payment_receipt_id
WHERE epr.id = $1
`

type ClassEventFetchByPaymentIDRow struct {
	ID    uuid.UUID `json:"id"`
	Price int32     `json:"price"`
	Name  string    `json:"name"`
}

func (q *Queries) ClassEventFetchByPaymentID(ctx context.Context, id uuid.UUID) ([]ClassEventFetchByPaymentIDRow, error) {
	rows, err := q.db.QueryContext(ctx, classEventFetchByPaymentID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClassEventFetchByPaymentIDRow{}
	for rows.Next() {
		var i ClassEventFetchByPaymentIDRow
		if err := rows.Scan(&i.ID, &i.Price, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const classEventFetchLastMatchIndexByEventID = `-- name: ClassEventFetchLastMatchIndexByEventID :one
SELECT MAX(match_index)::int as last_match_index FROM class_events WHERE event_id = $1
`

func (q *Queries) ClassEventFetchLastMatchIndexByEventID(ctx context.Context, eventID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, classEventFetchLastMatchIndexByEventID, eventID)
	var last_match_index int32
	err := row.Scan(&last_match_index)
	return last_match_index, err
}

const classEventFetchOne = `-- name: ClassEventFetchOne :one
SELECT ce.id, c.match_type, ce.bracket_generate, ce.bracket_lock, ce.score_lock, ce.price, ccr.male as rule_male,
       ccr.female as rule_female, ccr.total as rule_total, ce.event_id, ce.match_index
FROM class_events as ce
INNER JOIN classes as c ON c.id = ce.class_id
INNER JOIN class_competition_rules as ccr ON ccr.id = c.class_competition_rule_id
WHERE ce.id = $1
`

type ClassEventFetchOneRow struct {
	ID              uuid.UUID `json:"id"`
	MatchType       MatchType `json:"match_type"`
	BracketGenerate bool      `json:"bracket_generate"`
	BracketLock     bool      `json:"bracket_lock"`
	ScoreLock       bool      `json:"score_lock"`
	Price           int32     `json:"price"`
	RuleMale        int16     `json:"rule_male"`
	RuleFemale      int16     `json:"rule_female"`
	RuleTotal       int16     `json:"rule_total"`
	EventID         uuid.UUID `json:"event_id"`
	MatchIndex      int16     `json:"match_index"`
}

func (q *Queries) ClassEventFetchOne(ctx context.Context, id uuid.UUID) (ClassEventFetchOneRow, error) {
	row := q.db.QueryRowContext(ctx, classEventFetchOne, id)
	var i ClassEventFetchOneRow
	err := row.Scan(
		&i.ID,
		&i.MatchType,
		&i.BracketGenerate,
		&i.BracketLock,
		&i.ScoreLock,
		&i.Price,
		&i.RuleMale,
		&i.RuleFemale,
		&i.RuleTotal,
		&i.EventID,
		&i.MatchIndex,
	)
	return i, err
}

const classEventFetchSingleByEventIDAndLockStatus = `-- name: ClassEventFetchSingleByEventIDAndLockStatus :many
SELECT ce.id FROM class_events as ce
INNER JOIN classes as c ON c.id = ce.class_id
WHERE c.match_type = 'single' AND ce.bracket_lock = false AND ce.event_id = $1
`

func (q *Queries) ClassEventFetchSingleByEventIDAndLockStatus(ctx context.Context, eventID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, classEventFetchSingleByEventIDAndLockStatus, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const classEventUpdate = `-- name: ClassEventUpdate :exec
UPDATE class_events SET price = $1,
                        updated_at = NOW()
WHERE id = $2
`

type ClassEventUpdateParams struct {
	Price int32     `json:"price"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) ClassEventUpdate(ctx context.Context, arg ClassEventUpdateParams) error {
	_, err := q.db.ExecContext(ctx, classEventUpdate, arg.Price, arg.ID)
	return err
}

const classEventUpdateBracketGenerate = `-- name: ClassEventUpdateBracketGenerate :exec
UPDATE class_events SET bracket_generate = $1,
                        match_index = $2,
                        updated_at = NOW()
WHERE id = $3
`

type ClassEventUpdateBracketGenerateParams struct {
	BracketGenerate bool      `json:"bracket_generate"`
	MatchIndex      int16     `json:"match_index"`
	ID              uuid.UUID `json:"id"`
}

func (q *Queries) ClassEventUpdateBracketGenerate(ctx context.Context, arg ClassEventUpdateBracketGenerateParams) error {
	_, err := q.db.ExecContext(ctx, classEventUpdateBracketGenerate, arg.BracketGenerate, arg.MatchIndex, arg.ID)
	return err
}

const classEventUpdateBracketLock = `-- name: ClassEventUpdateBracketLock :exec
UPDATE class_events SET bracket_lock = $1,
                        updated_at = NOW()
WHERE id = $2
`

type ClassEventUpdateBracketLockParams struct {
	BracketLock bool      `json:"bracket_lock"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) ClassEventUpdateBracketLock(ctx context.Context, arg ClassEventUpdateBracketLockParams) error {
	_, err := q.db.ExecContext(ctx, classEventUpdateBracketLock, arg.BracketLock, arg.ID)
	return err
}

const classEventUpdateScoreLock = `-- name: ClassEventUpdateScoreLock :exec
UPDATE class_events SET score_lock = $1,
                        updated_at = NOW()
WHERE id = $2
`

type ClassEventUpdateScoreLockParams struct {
	ScoreLock bool      `json:"score_lock"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) ClassEventUpdateScoreLock(ctx context.Context, arg ClassEventUpdateScoreLockParams) error {
	_, err := q.db.ExecContext(ctx, classEventUpdateScoreLock, arg.ScoreLock, arg.ID)
	return err
}

const classEventWithParticipantsByPaymentID = `-- name: ClassEventWithParticipantsByPaymentID :many
SELECT DISTINCT ce.id, ce.price, c.name, array(SELECT ) FROM class_events as ce
INNER JOIN classes as c ON c.id = ce.class_id
INNER JOIN event_registrations as er ON er.class_event_id = ce.id
INNER JOIN event_payment_receipts as epr ON epr.id = er.event_payment_receipt_id
WHERE epr.id = $1
`

type ClassEventWithParticipantsByPaymentIDRow struct {
	ID     uuid.UUID   `json:"id"`
	Price  int32       `json:"price"`
	Name   string      `json:"name"`
	Exists interface{} `json:"exists"`
}

func (q *Queries) ClassEventWithParticipantsByPaymentID(ctx context.Context, id uuid.UUID) ([]ClassEventWithParticipantsByPaymentIDRow, error) {
	rows, err := q.db.QueryContext(ctx, classEventWithParticipantsByPaymentID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClassEventWithParticipantsByPaymentIDRow{}
	for rows.Next() {
		var i ClassEventWithParticipantsByPaymentIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Price,
			&i.Name,
			&i.Exists,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
