// Code generated by sqlc. DO NOT EDIT.
// source: club.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const clubCheckByIDAndUserID = `-- name: ClubCheckByIDAndUserID :one
SELECT id FROM clubs WHERE id = $1 AND user_id = $2
`

type ClubCheckByIDAndUserIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ClubCheckByIDAndUserID(ctx context.Context, arg ClubCheckByIDAndUserIDParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, clubCheckByIDAndUserID, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const clubCheckOne = `-- name: ClubCheckOne :one
SELECT id FROM clubs WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL LIMIT 1
`

type ClubCheckOneParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ClubCheckOne(ctx context.Context, arg ClubCheckOneParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, clubCheckOne, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const clubCheckOneWithoutUserID = `-- name: ClubCheckOneWithoutUserID :one
SELECT id, name FROM clubs WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

type ClubCheckOneWithoutUserIDRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) ClubCheckOneWithoutUserID(ctx context.Context, id uuid.UUID) (ClubCheckOneWithoutUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, clubCheckOneWithoutUserID, id)
	var i ClubCheckOneWithoutUserIDRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const clubCreate = `-- name: ClubCreate :one
INSERT INTO clubs(name, logo, phone, short_name, user_id, updated_at) VALUES ($1, $2, $3, $4, $5, NOW()) RETURNING id
`

type ClubCreateParams struct {
	Name      string    `json:"name"`
	Logo      string    `json:"logo"`
	Phone     string    `json:"phone"`
	ShortName string    `json:"short_name"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) ClubCreate(ctx context.Context, arg ClubCreateParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, clubCreate,
		arg.Name,
		arg.Logo,
		arg.Phone,
		arg.ShortName,
		arg.UserID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const clubDelete = `-- name: ClubDelete :exec
UPDATE clubs SET deleted_at = NOW() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) ClubDelete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clubDelete, id)
	return err
}

const clubFetchAllOwner = `-- name: ClubFetchAllOwner :many
SELECT id, name, logo FROM clubs WHERE user_id = $1
`

type ClubFetchAllOwnerRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
	Logo string    `json:"logo"`
}

func (q *Queries) ClubFetchAllOwner(ctx context.Context, userID uuid.UUID) ([]ClubFetchAllOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, clubFetchAllOwner, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClubFetchAllOwnerRow{}
	for rows.Next() {
		var i ClubFetchAllOwnerRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Logo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clubFetchByUserID = `-- name: ClubFetchByUserID :many
SELECT c.id, c.name FROM clubs as c
INNER JOIN club_participants as cp ON c.id = cp.club_id AND cp.club_approval = TRUE AND cp.user_approval = TRUE
WHERE cp.user_id = $1
`

type ClubFetchByUserIDRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) ClubFetchByUserID(ctx context.Context, userID uuid.UUID) ([]ClubFetchByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, clubFetchByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClubFetchByUserIDRow{}
	for rows.Next() {
		var i ClubFetchByUserIDRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clubFetchOne = `-- name: ClubFetchOne :one
SELECT clubs.id, clubs.name, clubs.logo, clubs.short_name, users.name as owner FROM clubs
INNER JOIN users ON users.id = clubs.user_id
WHERE clubs.id = $1
ORDER BY clubs.created_at DESC
LIMIT 1
`

type ClubFetchOneRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Logo      string    `json:"logo"`
	ShortName string    `json:"short_name"`
	Owner     string    `json:"owner"`
}

func (q *Queries) ClubFetchOne(ctx context.Context, id uuid.UUID) (ClubFetchOneRow, error) {
	row := q.db.QueryRowContext(ctx, clubFetchOne, id)
	var i ClubFetchOneRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Logo,
		&i.ShortName,
		&i.Owner,
	)
	return i, err
}

const clubFetchOneOwner = `-- name: ClubFetchOneOwner :one
SELECT id FROM clubs WHERE user_id = $1 AND id = $2 LIMIT 1
`

type ClubFetchOneOwnerParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) ClubFetchOneOwner(ctx context.Context, arg ClubFetchOneOwnerParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, clubFetchOneOwner, arg.UserID, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const clubFetchOwner = `-- name: ClubFetchOwner :one
SELECT id FROM clubs WHERE user_id = $1 LIMIT 1
`

func (q *Queries) ClubFetchOwner(ctx context.Context, userID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, clubFetchOwner, userID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const clubFetchOwnerByEventID = `-- name: ClubFetchOwnerByEventID :many
SELECT c.id FROM clubs as c
INNER JOIN event_registrations as er ON er.club_Id = c.id AND er.event_id = $1
WHERE user_id = $2
`

type ClubFetchOwnerByEventIDParams struct {
	EventID uuid.UUID `json:"event_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) ClubFetchOwnerByEventID(ctx context.Context, arg ClubFetchOwnerByEventIDParams) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, clubFetchOwnerByEventID, arg.EventID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clubHandover = `-- name: ClubHandover :exec
UPDATE clubs SET user_id = $1,
                 updated_at = NOW()
WHERE id = $2
`

type ClubHandoverParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) ClubHandover(ctx context.Context, arg ClubHandoverParams) error {
	_, err := q.db.ExecContext(ctx, clubHandover, arg.UserID, arg.ID)
	return err
}

const clubUpdate = `-- name: ClubUpdate :exec
UPDATE clubs SET name = $1,
                 logo = $2,
                 phone = $3,
                 short_name = $4,
                 updated_at = NOW()
WHERE id = $5 AND deleted_at IS NULL
`

type ClubUpdateParams struct {
	Name      string    `json:"name"`
	Logo      string    `json:"logo"`
	Phone     string    `json:"phone"`
	ShortName string    `json:"short_name"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) ClubUpdate(ctx context.Context, arg ClubUpdateParams) error {
	_, err := q.db.ExecContext(ctx, clubUpdate,
		arg.Name,
		arg.Logo,
		arg.Phone,
		arg.ShortName,
		arg.ID,
	)
	return err
}
