// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: club_participant.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const clubParticipantCreate = `-- name: ClubParticipantCreate :exec
INSERT INTO club_participants(club_id, user_id, club_approval, user_approval, updated_at) VALUES ($1, $2, TRUE, TRUE, NOW())
`

type ClubParticipantCreateParams struct {
	ClubID uuid.UUID `json:"club_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ClubParticipantCreate(ctx context.Context, arg ClubParticipantCreateParams) error {
	_, err := q.db.ExecContext(ctx, clubParticipantCreate, arg.ClubID, arg.UserID)
	return err
}
