// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: club.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const clubCreate = `-- name: ClubCreate :one
INSERT INTO clubs(name, logo, phone, short_name, user_id, updated_at) VALUES ($1, $2, $3, $4, $5, NOW()) RETURNING id
`

type ClubCreateParams struct {
	Name      string    `json:"name"`
	Logo      string    `json:"logo"`
	Phone     string    `json:"phone"`
	ShortName string    `json:"short_name"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) ClubCreate(ctx context.Context, arg ClubCreateParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, clubCreate,
		arg.Name,
		arg.Logo,
		arg.Phone,
		arg.ShortName,
		arg.UserID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
