// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: club_sport.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const clubAttachSport = `-- name: ClubAttachSport :exec
INSERT INTO club_sport(club_id, sport_id, updated_at) VALUES ($1, $2, NOW())
`

type ClubAttachSportParams struct {
	ClubID  uuid.UUID `json:"club_id"`
	SportID uuid.UUID `json:"sport_id"`
}

func (q *Queries) ClubAttachSport(ctx context.Context, arg ClubAttachSportParams) error {
	_, err := q.db.ExecContext(ctx, clubAttachSport, arg.ClubID, arg.SportID)
	return err
}
