// Code generated by sqlc. DO NOT EDIT.
// source: clubCertificate.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clubCertificateCountAllByClubID = `-- name: ClubCertificateCountAllByClubID :one
SELECT COUNT(id) FROM club_certificates WHERE club_id = $1
`

func (q *Queries) ClubCertificateCountAllByClubID(ctx context.Context, clubID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, clubCertificateCountAllByClubID, clubID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const clubCertificateCreate = `-- name: ClubCertificateCreate :exec
INSERT INTO club_certificates(id, club_id, event_id, reward_as, updated_at)
VALUES($1, $2, $3, $4, NOW())
`

type ClubCertificateCreateParams struct {
	ID       uuid.UUID `json:"id"`
	ClubID   uuid.UUID `json:"club_id"`
	EventID  uuid.UUID `json:"event_id"`
	RewardAs string    `json:"reward_as"`
}

func (q *Queries) ClubCertificateCreate(ctx context.Context, arg ClubCertificateCreateParams) error {
	_, err := q.db.ExecContext(ctx, clubCertificateCreate,
		arg.ID,
		arg.ClubID,
		arg.EventID,
		arg.RewardAs,
	)
	return err
}

const clubCertificateFetchAllByUserID = `-- name: ClubCertificateFetchAllByUserID :many
SELECT c.id, cl.name, e.name as event_name, e.thumbnail, c.reward_as, c.created_at FROM club_certificates as c
INNER JOIN clubs as cl ON cl.id = c.club_id
INNER JOIN events as e ON e.id = c.event_id
WHERE c.club_id = $1
ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ClubCertificateFetchAllByUserIDParams struct {
	ClubID uuid.UUID `json:"club_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ClubCertificateFetchAllByUserIDRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	EventName string    `json:"event_name"`
	Thumbnail string    `json:"thumbnail"`
	RewardAs  string    `json:"reward_as"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ClubCertificateFetchAllByUserID(ctx context.Context, arg ClubCertificateFetchAllByUserIDParams) ([]ClubCertificateFetchAllByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, clubCertificateFetchAllByUserID, arg.ClubID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClubCertificateFetchAllByUserIDRow{}
	for rows.Next() {
		var i ClubCertificateFetchAllByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EventName,
			&i.Thumbnail,
			&i.RewardAs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
