// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: document.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const documentCheckOne = `-- name: DocumentCheckOne :one
SELECT id FROM documents WHERE id = $1 AND user_id = $2 LIMIT 1
`

type DocumentCheckOneParams struct {
	ID     int64     `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DocumentCheckOne(ctx context.Context, arg DocumentCheckOneParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, documentCheckOne, arg.ID, arg.UserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const documentCountAll = `-- name: DocumentCountAll :one
SELECT COUNT(id) FROM documents WHERE user_id = $1 LIMIT 1
`

func (q *Queries) DocumentCountAll(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, documentCountAll, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const documentCreate = `-- name: DocumentCreate :exec
INSERT INTO documents(user_id, birth_certificate, family_card, user_identity, belt_certificate, elementary_certificate,
                      middle_certificate, high_certificate, bachelor_certificate, master_certificate, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7 ,$8 ,$9 ,$10, NOW())
`

type DocumentCreateParams struct {
	UserID                uuid.UUID `json:"user_id"`
	BirthCertificate      string    `json:"birth_certificate"`
	FamilyCard            string    `json:"family_card"`
	UserIdentity          string    `json:"user_identity"`
	BeltCertificate       string    `json:"belt_certificate"`
	ElementaryCertificate string    `json:"elementary_certificate"`
	MiddleCertificate     string    `json:"middle_certificate"`
	HighCertificate       string    `json:"high_certificate"`
	BachelorCertificate   string    `json:"bachelor_certificate"`
	MasterCertificate     string    `json:"master_certificate"`
}

func (q *Queries) DocumentCreate(ctx context.Context, arg DocumentCreateParams) error {
	_, err := q.db.ExecContext(ctx, documentCreate,
		arg.UserID,
		arg.BirthCertificate,
		arg.FamilyCard,
		arg.UserIdentity,
		arg.BeltCertificate,
		arg.ElementaryCertificate,
		arg.MiddleCertificate,
		arg.HighCertificate,
		arg.BachelorCertificate,
		arg.MasterCertificate,
	)
	return err
}

const documentDelete = `-- name: DocumentDelete :exec
DELETE FROM documents WHERE id = $1
`

func (q *Queries) DocumentDelete(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, documentDelete, id)
	return err
}

const documentFetchAll = `-- name: DocumentFetchAll :many
SELECT id, user_id, birth_certificate, family_card, user_identity, belt_certificate, elementary_certificate,
       middle_certificate, high_certificate, bachelor_certificate, master_certificate FROM documents
WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type DocumentFetchAllParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type DocumentFetchAllRow struct {
	ID                    int64     `json:"id"`
	UserID                uuid.UUID `json:"user_id"`
	BirthCertificate      string    `json:"birth_certificate"`
	FamilyCard            string    `json:"family_card"`
	UserIdentity          string    `json:"user_identity"`
	BeltCertificate       string    `json:"belt_certificate"`
	ElementaryCertificate string    `json:"elementary_certificate"`
	MiddleCertificate     string    `json:"middle_certificate"`
	HighCertificate       string    `json:"high_certificate"`
	BachelorCertificate   string    `json:"bachelor_certificate"`
	MasterCertificate     string    `json:"master_certificate"`
}

func (q *Queries) DocumentFetchAll(ctx context.Context, arg DocumentFetchAllParams) ([]DocumentFetchAllRow, error) {
	rows, err := q.db.QueryContext(ctx, documentFetchAll, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentFetchAllRow{}
	for rows.Next() {
		var i DocumentFetchAllRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BirthCertificate,
			&i.FamilyCard,
			&i.UserIdentity,
			&i.BeltCertificate,
			&i.ElementaryCertificate,
			&i.MiddleCertificate,
			&i.HighCertificate,
			&i.BachelorCertificate,
			&i.MasterCertificate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const documentUpdate = `-- name: DocumentUpdate :exec
UPDATE documents SET birth_certificate = $1,
                     family_card = $2,
                     user_identity = $3,
                     belt_certificate = $4,
                     elementary_certificate = $5,
                     middle_certificate = $6,
                     high_certificate = $7,
                     bachelor_certificate = $8,
                     master_certificate = $9,
                     updated_at = NOW()
WHERE id = $10
`

type DocumentUpdateParams struct {
	BirthCertificate      string `json:"birth_certificate"`
	FamilyCard            string `json:"family_card"`
	UserIdentity          string `json:"user_identity"`
	BeltCertificate       string `json:"belt_certificate"`
	ElementaryCertificate string `json:"elementary_certificate"`
	MiddleCertificate     string `json:"middle_certificate"`
	HighCertificate       string `json:"high_certificate"`
	BachelorCertificate   string `json:"bachelor_certificate"`
	MasterCertificate     string `json:"master_certificate"`
	ID                    int64  `json:"id"`
}

func (q *Queries) DocumentUpdate(ctx context.Context, arg DocumentUpdateParams) error {
	_, err := q.db.ExecContext(ctx, documentUpdate,
		arg.BirthCertificate,
		arg.FamilyCard,
		arg.UserIdentity,
		arg.BeltCertificate,
		arg.ElementaryCertificate,
		arg.MiddleCertificate,
		arg.HighCertificate,
		arg.BachelorCertificate,
		arg.MasterCertificate,
		arg.ID,
	)
	return err
}
