// Code generated by sqlc. DO NOT EDIT.
// source: event.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const eventCheckOne = `-- name: EventCheckOne :one
SELECT id, name, deadline, remark, is_generate FROM events WHERE deleted_at IS NULL AND id = $1
`

type EventCheckOneRow struct {
	ID         uuid.UUID  `json:"id"`
	Name       string     `json:"name"`
	Deadline   time.Time  `json:"deadline"`
	Remark     RemarkType `json:"remark"`
	IsGenerate bool       `json:"is_generate"`
}

func (q *Queries) EventCheckOne(ctx context.Context, id uuid.UUID) (EventCheckOneRow, error) {
	row := q.db.QueryRowContext(ctx, eventCheckOne, id)
	var i EventCheckOneRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Deadline,
		&i.Remark,
		&i.IsGenerate,
	)
	return i, err
}

const eventCountAll = `-- name: EventCountAll :one
SELECT COUNT(id) FROM events WHERE deleted_at IS NULL LIMIT 1
`

func (q *Queries) EventCountAll(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, eventCountAll)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const eventCountByRemark = `-- name: EventCountByRemark :one
SELECT COUNT(id) FROM events WHERE remark = $1
`

func (q *Queries) EventCountByRemark(ctx context.Context, remark RemarkType) (int64, error) {
	row := q.db.QueryRowContext(ctx, eventCountByRemark, remark)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const eventCountByUserID = `-- name: EventCountByUserID :one
SELECT COUNT(id) FROM events WHERE deleted_at IS NULL AND user_id = $1 LIMIT 1
`

func (q *Queries) EventCountByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, eventCountByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const eventCountCanceled = `-- name: EventCountCanceled :one
SELECT COUNT(id) FROM events WHERE remark = 'rejected'
`

func (q *Queries) EventCountCanceled(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, eventCountCanceled)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const eventCountInfinite = `-- name: EventCountInfinite :one
SELECT COUNT(id) FROM events WHERE remark != 'unconfirmed' AND remark != 'rejected'
`

func (q *Queries) EventCountInfinite(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, eventCountInfinite)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const eventCreate = `-- name: EventCreate :one
INSERT INTO events(user_id, type, name, description, prize_pool, location, province, city, thumbnail, start_date, end_date, deadline,
                   sport_id, rules, proposal_link, quota, open, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, NOW())
RETURNING id
`

type EventCreateParams struct {
	UserID       uuid.UUID `json:"user_id"`
	Type         EventType `json:"type"`
	Name         string    `json:"name"`
	Description  string    `json:"description"`
	PrizePool    string    `json:"prize_pool"`
	Location     string    `json:"location"`
	Province     string    `json:"province"`
	City         string    `json:"city"`
	Thumbnail    string    `json:"thumbnail"`
	StartDate    time.Time `json:"start_date"`
	EndDate      time.Time `json:"end_date"`
	Deadline     time.Time `json:"deadline"`
	SportID      uuid.UUID `json:"sport_id"`
	Rules        string    `json:"rules"`
	ProposalLink string    `json:"proposal_link"`
	Quota        int32     `json:"quota"`
	Open         time.Time `json:"open"`
}

func (q *Queries) EventCreate(ctx context.Context, arg EventCreateParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, eventCreate,
		arg.UserID,
		arg.Type,
		arg.Name,
		arg.Description,
		arg.PrizePool,
		arg.Location,
		arg.Province,
		arg.City,
		arg.Thumbnail,
		arg.StartDate,
		arg.EndDate,
		arg.Deadline,
		arg.SportID,
		arg.Rules,
		arg.ProposalLink,
		arg.Quota,
		arg.Open,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const eventDelete = `-- name: EventDelete :exec
UPDATE events SET deleted_at = NOW(),
                  updated_at = NOW()
WHERE id = $1
`

func (q *Queries) EventDelete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, eventDelete, id)
	return err
}

const eventFetchAll = `-- name: EventFetchAll :many
SELECT e.id, e.user_id, u.name as user_name, e.type, e.name, e.description, e.prize_pool, e.location, e.thumbnail, e.start_date, e.end_date,
       e.deadline, e.sport_id, e.remark, e.open, s.name as sport_name, e.rules, e.proposal_link, e.status, e.quota,
       e.province, e.city, u.photo as user_image
FROM events as e
INNER JOIN users as u ON e.user_id = u.id
INNER JOIN sports as s ON e.sport_id = s.id
WHERE e.deleted_at IS NULL
ORDER BY e.created_at DESC
LIMIT $1 OFFSET $2
`

type EventFetchAllParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type EventFetchAllRow struct {
	ID           uuid.UUID    `json:"id"`
	UserID       uuid.UUID    `json:"user_id"`
	UserName     string       `json:"user_name"`
	Type         EventType    `json:"type"`
	Name         string       `json:"name"`
	Description  string       `json:"description"`
	PrizePool    string       `json:"prize_pool"`
	Location     string       `json:"location"`
	Thumbnail    string       `json:"thumbnail"`
	StartDate    time.Time    `json:"start_date"`
	EndDate      time.Time    `json:"end_date"`
	Deadline     time.Time    `json:"deadline"`
	SportID      uuid.UUID    `json:"sport_id"`
	Remark       RemarkType   `json:"remark"`
	Open         time.Time    `json:"open"`
	SportName    string       `json:"sport_name"`
	Rules        string       `json:"rules"`
	ProposalLink string       `json:"proposal_link"`
	Status       sql.NullBool `json:"status"`
	Quota        int32        `json:"quota"`
	Province     string       `json:"province"`
	City         string       `json:"city"`
	UserImage    string       `json:"user_image"`
}

func (q *Queries) EventFetchAll(ctx context.Context, arg EventFetchAllParams) ([]EventFetchAllRow, error) {
	rows, err := q.db.QueryContext(ctx, eventFetchAll, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventFetchAllRow{}
	for rows.Next() {
		var i EventFetchAllRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserName,
			&i.Type,
			&i.Name,
			&i.Description,
			&i.PrizePool,
			&i.Location,
			&i.Thumbnail,
			&i.StartDate,
			&i.EndDate,
			&i.Deadline,
			&i.SportID,
			&i.Remark,
			&i.Open,
			&i.SportName,
			&i.Rules,
			&i.ProposalLink,
			&i.Status,
			&i.Quota,
			&i.Province,
			&i.City,
			&i.UserImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventFetchAllMostParticipant = `-- name: EventFetchAllMostParticipant :many
SELECT e.name, COUNT(er.id) as total FROM events as e
INNER JOIN event_registrations as er ON er.event_id = e.id
GROUP BY e.id, e.name, e.remark
HAVING e.remark = 'done'
ORDER BY total DESC
LIMIT 10
`

type EventFetchAllMostParticipantRow struct {
	Name  string `json:"name"`
	Total int64  `json:"total"`
}

func (q *Queries) EventFetchAllMostParticipant(ctx context.Context) ([]EventFetchAllMostParticipantRow, error) {
	rows, err := q.db.QueryContext(ctx, eventFetchAllMostParticipant)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventFetchAllMostParticipantRow{}
	for rows.Next() {
		var i EventFetchAllMostParticipantRow
		if err := rows.Scan(&i.Name, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventFetchAllMostSport = `-- name: EventFetchAllMostSport :many
SELECT s.name, COUNT(e.id) as total FROM events as e
INNER JOIN sports as s ON s.id = e.sport_id
GROUP BY e.sport_id, s.name, e.remark
HAVING e.remark = 'done'
ORDER BY total DESC
LIMIT 10
`

type EventFetchAllMostSportRow struct {
	Name  string `json:"name"`
	Total int64  `json:"total"`
}

func (q *Queries) EventFetchAllMostSport(ctx context.Context) ([]EventFetchAllMostSportRow, error) {
	rows, err := q.db.QueryContext(ctx, eventFetchAllMostSport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventFetchAllMostSportRow{}
	for rows.Next() {
		var i EventFetchAllMostSportRow
		if err := rows.Scan(&i.Name, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventFetchByRemarkClose = `-- name: EventFetchByRemarkClose :many
SELECT id, start_date FROM events WHERE remark = 'closed' AND is_generate = true AND start_date <= NOW()  AND status = TRUE
`

type EventFetchByRemarkCloseRow struct {
	ID        uuid.UUID `json:"id"`
	StartDate time.Time `json:"start_date"`
}

func (q *Queries) EventFetchByRemarkClose(ctx context.Context) ([]EventFetchByRemarkCloseRow, error) {
	rows, err := q.db.QueryContext(ctx, eventFetchByRemarkClose)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventFetchByRemarkCloseRow{}
	for rows.Next() {
		var i EventFetchByRemarkCloseRow
		if err := rows.Scan(&i.ID, &i.StartDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventFetchByRemarkOngoing = `-- name: EventFetchByRemarkOngoing :many
SELECT id, end_date FROM events WHERE remark = 'ongoing' AND end_date < NOW()  AND status = TRUE
`

type EventFetchByRemarkOngoingRow struct {
	ID      uuid.UUID `json:"id"`
	EndDate time.Time `json:"end_date"`
}

func (q *Queries) EventFetchByRemarkOngoing(ctx context.Context) ([]EventFetchByRemarkOngoingRow, error) {
	rows, err := q.db.QueryContext(ctx, eventFetchByRemarkOngoing)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventFetchByRemarkOngoingRow{}
	for rows.Next() {
		var i EventFetchByRemarkOngoingRow
		if err := rows.Scan(&i.ID, &i.EndDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventFetchByRemarkOpen = `-- name: EventFetchByRemarkOpen :many
SELECT id, deadline FROM events WHERE remark = 'open' AND deadline <= NOW()  AND status = TRUE
`

type EventFetchByRemarkOpenRow struct {
	ID       uuid.UUID `json:"id"`
	Deadline time.Time `json:"deadline"`
}

func (q *Queries) EventFetchByRemarkOpen(ctx context.Context) ([]EventFetchByRemarkOpenRow, error) {
	rows, err := q.db.QueryContext(ctx, eventFetchByRemarkOpen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventFetchByRemarkOpenRow{}
	for rows.Next() {
		var i EventFetchByRemarkOpenRow
		if err := rows.Scan(&i.ID, &i.Deadline); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventFetchByRemarkSoon = `-- name: EventFetchByRemarkSoon :many
SELECT id, open FROM events WHERE remark = 'soon' AND open <= NOW()  AND status = TRUE
`

type EventFetchByRemarkSoonRow struct {
	ID   uuid.UUID `json:"id"`
	Open time.Time `json:"open"`
}

func (q *Queries) EventFetchByRemarkSoon(ctx context.Context) ([]EventFetchByRemarkSoonRow, error) {
	rows, err := q.db.QueryContext(ctx, eventFetchByRemarkSoon)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventFetchByRemarkSoonRow{}
	for rows.Next() {
		var i EventFetchByRemarkSoonRow
		if err := rows.Scan(&i.ID, &i.Open); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventFetchByUserID = `-- name: EventFetchByUserID :many
SELECT e.id, e.user_id, u.name as user_name, u.photo as user_image, e.type, e.name, e.description, e.prize_pool, e.location, e.thumbnail, e.start_date, e.end_date,
       e.deadline, e.sport_id, e.remark, e.open, s.name as sport_name, e.rules, e.proposal_link, e.status, e.quota,
       e.province, e.city
FROM events as e
         INNER JOIN event_privileges as ep ON ep.event_id = e.id AND ep.user_id = $1
         INNER JOIN users as u ON e.user_id = u.id
         INNER JOIN sports as s ON e.sport_id = s.id
WHERE e.deleted_at IS NULL
ORDER BY e.created_at DESC
LIMIT $2 OFFSET $3
`

type EventFetchByUserIDParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type EventFetchByUserIDRow struct {
	ID           uuid.UUID    `json:"id"`
	UserID       uuid.UUID    `json:"user_id"`
	UserName     string       `json:"user_name"`
	UserImage    string       `json:"user_image"`
	Type         EventType    `json:"type"`
	Name         string       `json:"name"`
	Description  string       `json:"description"`
	PrizePool    string       `json:"prize_pool"`
	Location     string       `json:"location"`
	Thumbnail    string       `json:"thumbnail"`
	StartDate    time.Time    `json:"start_date"`
	EndDate      time.Time    `json:"end_date"`
	Deadline     time.Time    `json:"deadline"`
	SportID      uuid.UUID    `json:"sport_id"`
	Remark       RemarkType   `json:"remark"`
	Open         time.Time    `json:"open"`
	SportName    string       `json:"sport_name"`
	Rules        string       `json:"rules"`
	ProposalLink string       `json:"proposal_link"`
	Status       sql.NullBool `json:"status"`
	Quota        int32        `json:"quota"`
	Province     string       `json:"province"`
	City         string       `json:"city"`
}

func (q *Queries) EventFetchByUserID(ctx context.Context, arg EventFetchByUserIDParams) ([]EventFetchByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, eventFetchByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventFetchByUserIDRow{}
	for rows.Next() {
		var i EventFetchByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserName,
			&i.UserImage,
			&i.Type,
			&i.Name,
			&i.Description,
			&i.PrizePool,
			&i.Location,
			&i.Thumbnail,
			&i.StartDate,
			&i.EndDate,
			&i.Deadline,
			&i.SportID,
			&i.Remark,
			&i.Open,
			&i.SportName,
			&i.Rules,
			&i.ProposalLink,
			&i.Status,
			&i.Quota,
			&i.Province,
			&i.City,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventFetchForCart = `-- name: EventFetchForCart :one
SELECT u.name as event_owner, e.name as event_name, s.name as sport_name, e.thumbnail, e.deadline
FROM events as e
INNER JOIN users as u ON u.id = e.user_id
INNER JOIN sports as s ON s.id = e.sport_id
WHERE e.id = $1
`

type EventFetchForCartRow struct {
	EventOwner string    `json:"event_owner"`
	EventName  string    `json:"event_name"`
	SportName  string    `json:"sport_name"`
	Thumbnail  string    `json:"thumbnail"`
	Deadline   time.Time `json:"deadline"`
}

func (q *Queries) EventFetchForCart(ctx context.Context, id uuid.UUID) (EventFetchForCartRow, error) {
	row := q.db.QueryRowContext(ctx, eventFetchForCart, id)
	var i EventFetchForCartRow
	err := row.Scan(
		&i.EventOwner,
		&i.EventName,
		&i.SportName,
		&i.Thumbnail,
		&i.Deadline,
	)
	return i, err
}

const eventFetchMostParticipant = `-- name: EventFetchMostParticipant :one
SELECT e.id, e.name, COUNT(er.id) as total FROM events as e
INNER JOIN event_registrations as er ON er.event_id = e.id
GROUP BY e.id, e.name, e.remark
HAVING e.remark = 'done'
ORDER BY total DESC
`

type EventFetchMostParticipantRow struct {
	ID    uuid.UUID `json:"id"`
	Name  string    `json:"name"`
	Total int64     `json:"total"`
}

func (q *Queries) EventFetchMostParticipant(ctx context.Context) (EventFetchMostParticipantRow, error) {
	row := q.db.QueryRowContext(ctx, eventFetchMostParticipant)
	var i EventFetchMostParticipantRow
	err := row.Scan(&i.ID, &i.Name, &i.Total)
	return i, err
}

const eventFetchMostSport = `-- name: EventFetchMostSport :one
SELECT e.sport_id, s.name, COUNT(e.id) as total FROM events as e
INNER JOIN sports as s ON s.id = e.sport_id
GROUP BY e.sport_id, s.name, e.remark
HAVING e.remark = 'done'
ORDER BY total DESC
`

type EventFetchMostSportRow struct {
	SportID uuid.UUID `json:"sport_id"`
	Name    string    `json:"name"`
	Total   int64     `json:"total"`
}

func (q *Queries) EventFetchMostSport(ctx context.Context) (EventFetchMostSportRow, error) {
	row := q.db.QueryRowContext(ctx, eventFetchMostSport)
	var i EventFetchMostSportRow
	err := row.Scan(&i.SportID, &i.Name, &i.Total)
	return i, err
}

const eventFetchOne = `-- name: EventFetchOne :one
SELECT e.id, e.user_id, u.name as user_name, u.photo as user_image, e.type, e.name, e.description, e.prize_pool, e.location, e.thumbnail, e.start_date, e.end_date,
    e.deadline, e.sport_id, s.name as sport_name, e.rules, e.proposal_link, e.status, e.quota, e.remark, e.open,
       e.province, e.city, e.is_generate
FROM events as e
    INNER JOIN users as u ON e.user_id = u.id
    INNER JOIN sports as s ON e.sport_id = s.id
WHERE e.deleted_at IS NULL
AND e.id = $1 LIMIT 1
`

type EventFetchOneRow struct {
	ID           uuid.UUID    `json:"id"`
	UserID       uuid.UUID    `json:"user_id"`
	UserName     string       `json:"user_name"`
	UserImage    string       `json:"user_image"`
	Type         EventType    `json:"type"`
	Name         string       `json:"name"`
	Description  string       `json:"description"`
	PrizePool    string       `json:"prize_pool"`
	Location     string       `json:"location"`
	Thumbnail    string       `json:"thumbnail"`
	StartDate    time.Time    `json:"start_date"`
	EndDate      time.Time    `json:"end_date"`
	Deadline     time.Time    `json:"deadline"`
	SportID      uuid.UUID    `json:"sport_id"`
	SportName    string       `json:"sport_name"`
	Rules        string       `json:"rules"`
	ProposalLink string       `json:"proposal_link"`
	Status       sql.NullBool `json:"status"`
	Quota        int32        `json:"quota"`
	Remark       RemarkType   `json:"remark"`
	Open         time.Time    `json:"open"`
	Province     string       `json:"province"`
	City         string       `json:"city"`
	IsGenerate   bool         `json:"is_generate"`
}

func (q *Queries) EventFetchOne(ctx context.Context, id uuid.UUID) (EventFetchOneRow, error) {
	row := q.db.QueryRowContext(ctx, eventFetchOne, id)
	var i EventFetchOneRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserName,
		&i.UserImage,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.PrizePool,
		&i.Location,
		&i.Thumbnail,
		&i.StartDate,
		&i.EndDate,
		&i.Deadline,
		&i.SportID,
		&i.SportName,
		&i.Rules,
		&i.ProposalLink,
		&i.Status,
		&i.Quota,
		&i.Remark,
		&i.Open,
		&i.Province,
		&i.City,
		&i.IsGenerate,
	)
	return i, err
}

const eventFetchOneByIDAndUserID = `-- name: EventFetchOneByIDAndUserID :one
SELECT id FROM events WHERE id = $1 AND user_id = $2 LIMIT 1
`

type EventFetchOneByIDAndUserIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) EventFetchOneByIDAndUserID(ctx context.Context, arg EventFetchOneByIDAndUserIDParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, eventFetchOneByIDAndUserID, arg.ID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const eventFetchOneInfiniteByID = `-- name: EventFetchOneInfiniteByID :one
SELECT e.id, e.user_id, u.name as user_name, e.type, e.name, e.description, e.prize_pool, e.location, e.thumbnail, e.start_date, e.end_date,
       e.deadline, e.sport_id, s.name as sport_name, e.order_number, e.quota, e.remark, e.open, e.province, e.city, u.photo as user_image
FROM events as e
         INNER JOIN users as u ON e.user_id = u.id
         INNER JOIN sports as s ON e.sport_id = s.id
WHERE e.deleted_at IS NULL AND e.remark != 'unconfirmed' AND e.status = TRUE AND e.id = $1
`

type EventFetchOneInfiniteByIDRow struct {
	ID          uuid.UUID  `json:"id"`
	UserID      uuid.UUID  `json:"user_id"`
	UserName    string     `json:"user_name"`
	Type        EventType  `json:"type"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	PrizePool   string     `json:"prize_pool"`
	Location    string     `json:"location"`
	Thumbnail   string     `json:"thumbnail"`
	StartDate   time.Time  `json:"start_date"`
	EndDate     time.Time  `json:"end_date"`
	Deadline    time.Time  `json:"deadline"`
	SportID     uuid.UUID  `json:"sport_id"`
	SportName   string     `json:"sport_name"`
	OrderNumber int64      `json:"order_number"`
	Quota       int32      `json:"quota"`
	Remark      RemarkType `json:"remark"`
	Open        time.Time  `json:"open"`
	Province    string     `json:"province"`
	City        string     `json:"city"`
	UserImage   string     `json:"user_image"`
}

func (q *Queries) EventFetchOneInfiniteByID(ctx context.Context, id uuid.UUID) (EventFetchOneInfiniteByIDRow, error) {
	row := q.db.QueryRowContext(ctx, eventFetchOneInfiniteByID, id)
	var i EventFetchOneInfiniteByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserName,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.PrizePool,
		&i.Location,
		&i.Thumbnail,
		&i.StartDate,
		&i.EndDate,
		&i.Deadline,
		&i.SportID,
		&i.SportName,
		&i.OrderNumber,
		&i.Quota,
		&i.Remark,
		&i.Open,
		&i.Province,
		&i.City,
		&i.UserImage,
	)
	return i, err
}

const eventUpdate = `-- name: EventUpdate :exec
UPDATE events SET name = $1,
                  type = $2,
                  description = $3,
                  prize_pool = $4,
                  location = $5,
                  province = $6,
                  city = $7,
                  thumbnail = $8,
                  start_date = $9,
                  end_date = $10,
                  deadline = $11,
                  sport_id = $12,
                  rules = $13,
                  proposal_link = $14,
                  quota = $15,
                  open = $16,
                  updated_at = NOW()
WHERE id = $17
`

type EventUpdateParams struct {
	Name         string    `json:"name"`
	Type         EventType `json:"type"`
	Description  string    `json:"description"`
	PrizePool    string    `json:"prize_pool"`
	Location     string    `json:"location"`
	Province     string    `json:"province"`
	City         string    `json:"city"`
	Thumbnail    string    `json:"thumbnail"`
	StartDate    time.Time `json:"start_date"`
	EndDate      time.Time `json:"end_date"`
	Deadline     time.Time `json:"deadline"`
	SportID      uuid.UUID `json:"sport_id"`
	Rules        string    `json:"rules"`
	ProposalLink string    `json:"proposal_link"`
	Quota        int32     `json:"quota"`
	Open         time.Time `json:"open"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) EventUpdate(ctx context.Context, arg EventUpdateParams) error {
	_, err := q.db.ExecContext(ctx, eventUpdate,
		arg.Name,
		arg.Type,
		arg.Description,
		arg.PrizePool,
		arg.Location,
		arg.Province,
		arg.City,
		arg.Thumbnail,
		arg.StartDate,
		arg.EndDate,
		arg.Deadline,
		arg.SportID,
		arg.Rules,
		arg.ProposalLink,
		arg.Quota,
		arg.Open,
		arg.ID,
	)
	return err
}

const eventUpdateIsGenerate = `-- name: EventUpdateIsGenerate :exec
UPDATE events SET is_generate = $1,
                  updated_at = NOW()
WHERE id = $2
`

type EventUpdateIsGenerateParams struct {
	IsGenerate bool      `json:"is_generate"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) EventUpdateIsGenerate(ctx context.Context, arg EventUpdateIsGenerateParams) error {
	_, err := q.db.ExecContext(ctx, eventUpdateIsGenerate, arg.IsGenerate, arg.ID)
	return err
}

const eventUpdateRemark = `-- name: EventUpdateRemark :exec
UPDATE events SET remark = $1,
                  updated_at = NOW()
WHERE id = $2
`

type EventUpdateRemarkParams struct {
	Remark RemarkType `json:"remark"`
	ID     uuid.UUID  `json:"id"`
}

func (q *Queries) EventUpdateRemark(ctx context.Context, arg EventUpdateRemarkParams) error {
	_, err := q.db.ExecContext(ctx, eventUpdateRemark, arg.Remark, arg.ID)
	return err
}

const eventUpdateStatus = `-- name: EventUpdateStatus :exec
UPDATE events SET status = $1,
                  remark = $2,
                  updated_at = NOW()
WHERE id = $3
`

type EventUpdateStatusParams struct {
	Status sql.NullBool `json:"status"`
	Remark RemarkType   `json:"remark"`
	ID     uuid.UUID    `json:"id"`
}

func (q *Queries) EventUpdateStatus(ctx context.Context, arg EventUpdateStatusParams) error {
	_, err := q.db.ExecContext(ctx, eventUpdateStatus, arg.Status, arg.Remark, arg.ID)
	return err
}
