// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: eventRefund.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const eventRefundCreate = `-- name: EventRefundCreate :exec
INSERT INTO event_refunds(event_id, event_payment_receipt_id, note, admin_id, updated_at)
VALUES ($1, $2, $3, $4, NOW())
`

type EventRefundCreateParams struct {
	EventID               uuid.UUID `json:"event_id"`
	EventPaymentReceiptID uuid.UUID `json:"event_payment_receipt_id"`
	Note                  string    `json:"note"`
	AdminID               uuid.UUID `json:"admin_id"`
}

func (q *Queries) EventRefundCreate(ctx context.Context, arg EventRefundCreateParams) error {
	_, err := q.db.ExecContext(ctx, eventRefundCreate,
		arg.EventID,
		arg.EventPaymentReceiptID,
		arg.Note,
		arg.AdminID,
	)
	return err
}

const eventRefundFetchOne = `-- name: EventRefundFetchOne :one
SELECT id, event_payment_receipt_id, status FROM event_refunds WHERE id = $1
`

type EventRefundFetchOneRow struct {
	ID                    uuid.UUID         `json:"id"`
	EventPaymentReceiptID uuid.UUID         `json:"event_payment_receipt_id"`
	Status                EventRefundStatus `json:"status"`
}

func (q *Queries) EventRefundFetchOne(ctx context.Context, id uuid.UUID) (EventRefundFetchOneRow, error) {
	row := q.db.QueryRowContext(ctx, eventRefundFetchOne, id)
	var i EventRefundFetchOneRow
	err := row.Scan(&i.ID, &i.EventPaymentReceiptID, &i.Status)
	return i, err
}

const eventRefundUpdate = `-- name: EventRefundUpdate :exec
UPDATE event_refunds SET status = $1,
                         admin_id = $2,
                         updated_at = NOW()
WHERE id = $3
`

type EventRefundUpdateParams struct {
	Status  EventRefundStatus `json:"status"`
	AdminID uuid.UUID         `json:"admin_id"`
	ID      uuid.UUID         `json:"id"`
}

func (q *Queries) EventRefundUpdate(ctx context.Context, arg EventRefundUpdateParams) error {
	_, err := q.db.ExecContext(ctx, eventRefundUpdate, arg.Status, arg.AdminID, arg.ID)
	return err
}
