// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: eventRegistration.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const eventRegistrationCountAllByStatusApproved = `-- name: EventRegistrationCountAllByStatusApproved :one
SELECT COUNT(id) FROM event_registrations WHERE event_id = $1 AND status = 'approved'
`

func (q *Queries) EventRegistrationCountAllByStatusApproved(ctx context.Context, eventID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, eventRegistrationCountAllByStatusApproved, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const eventRegistrationCountByEventIDAndClubID = `-- name: EventRegistrationCountByEventIDAndClubID :one
SELECT COUNT(id) FROM event_registrations
WHERE event_id = $1 AND club_id = $2 AND status = 'approved'
`

type EventRegistrationCountByEventIDAndClubIDParams struct {
	EventID uuid.UUID `json:"event_id"`
	ClubID  uuid.UUID `json:"club_id"`
}

func (q *Queries) EventRegistrationCountByEventIDAndClubID(ctx context.Context, arg EventRegistrationCountByEventIDAndClubIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, eventRegistrationCountByEventIDAndClubID, arg.EventID, arg.ClubID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const eventRegistrationCountCart = `-- name: EventRegistrationCountCart :one
SELECT COUNT(*) FROM (SELECT e.id, e.name, e.thumbnail, SUM(ce.price) as total FROM event_registrations as er
    INNER JOIN events as e ON e.id = er.event_id
    INNER JOIN class_events as ce ON ce.id = er.class_event_id
    INNER JOIN clubs as c ON c.id = er.club_id
    WHERE er.status = 'pending' AND c.user_id = $1
    GROUP BY e.id) as carts
`

func (q *Queries) EventRegistrationCountCart(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, eventRegistrationCountCart, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const eventRegistrationCreate = `-- name: EventRegistrationCreate :one
INSERT INTO event_registrations(event_id, class_event_id, club_id, event_payment_receipt_id, status, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
RETURNING id
`

type EventRegistrationCreateParams struct {
	EventID               uuid.UUID               `json:"event_id"`
	ClassEventID          uuid.UUID               `json:"class_event_id"`
	ClubID                uuid.UUID               `json:"club_id"`
	EventPaymentReceiptID uuid.UUID               `json:"event_payment_receipt_id"`
	Status                EventRegistrationStatus `json:"status"`
}

func (q *Queries) EventRegistrationCreate(ctx context.Context, arg EventRegistrationCreateParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, eventRegistrationCreate,
		arg.EventID,
		arg.ClassEventID,
		arg.ClubID,
		arg.EventPaymentReceiptID,
		arg.Status,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const eventRegistrationFetchByClassEventID = `-- name: EventRegistrationFetchByClassEventID :many
SELECT er.id, er.event_id, er.class_event_id, er.club_id, er.status, c.name as club_name FROM event_registrations as er
INNER JOIN clubs as c ON c.id = er.club_id
WHERE status = 'approved' AND class_event_id = $1
`

type EventRegistrationFetchByClassEventIDRow struct {
	ID           uuid.UUID               `json:"id"`
	EventID      uuid.UUID               `json:"event_id"`
	ClassEventID uuid.UUID               `json:"class_event_id"`
	ClubID       uuid.UUID               `json:"club_id"`
	Status       EventRegistrationStatus `json:"status"`
	ClubName     string                  `json:"club_name"`
}

func (q *Queries) EventRegistrationFetchByClassEventID(ctx context.Context, classEventID uuid.UUID) ([]EventRegistrationFetchByClassEventIDRow, error) {
	rows, err := q.db.QueryContext(ctx, eventRegistrationFetchByClassEventID, classEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventRegistrationFetchByClassEventIDRow{}
	for rows.Next() {
		var i EventRegistrationFetchByClassEventIDRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ClassEventID,
			&i.ClubID,
			&i.Status,
			&i.ClubName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventRegistrationFetchByClassEventIDAndStatus = `-- name: EventRegistrationFetchByClassEventIDAndStatus :many
SELECT er.id, c.name as class_name,cl.name as club_name, er.status, er.club_id, er.class_event_id, ce.price FROM event_registrations as er
INNER JOIN class_events as ce ON ce.id = er.class_event_id
INNER JOIN classes as c ON c.id = ce.class_id
INNER JOIN clubs as cl ON cl.id = er.club_id
WHERE er.class_event_id = $1 AND er.status = 'approved'
`

type EventRegistrationFetchByClassEventIDAndStatusRow struct {
	ID           uuid.UUID               `json:"id"`
	ClassName    string                  `json:"class_name"`
	ClubName     string                  `json:"club_name"`
	Status       EventRegistrationStatus `json:"status"`
	ClubID       uuid.UUID               `json:"club_id"`
	ClassEventID uuid.UUID               `json:"class_event_id"`
	Price        int32                   `json:"price"`
}

func (q *Queries) EventRegistrationFetchByClassEventIDAndStatus(ctx context.Context, classEventID uuid.UUID) ([]EventRegistrationFetchByClassEventIDAndStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, eventRegistrationFetchByClassEventIDAndStatus, classEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventRegistrationFetchByClassEventIDAndStatusRow{}
	for rows.Next() {
		var i EventRegistrationFetchByClassEventIDAndStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.ClassName,
			&i.ClubName,
			&i.Status,
			&i.ClubID,
			&i.ClassEventID,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventRegistrationFetchByPaymentID = `-- name: EventRegistrationFetchByPaymentID :many
SELECT id, event_id, class_event_id, club_id, status FROM event_registrations
WHERE event_payment_receipt_id = $1
`

type EventRegistrationFetchByPaymentIDRow struct {
	ID           uuid.UUID               `json:"id"`
	EventID      uuid.UUID               `json:"event_id"`
	ClassEventID uuid.UUID               `json:"class_event_id"`
	ClubID       uuid.UUID               `json:"club_id"`
	Status       EventRegistrationStatus `json:"status"`
}

func (q *Queries) EventRegistrationFetchByPaymentID(ctx context.Context, eventPaymentReceiptID uuid.UUID) ([]EventRegistrationFetchByPaymentIDRow, error) {
	rows, err := q.db.QueryContext(ctx, eventRegistrationFetchByPaymentID, eventPaymentReceiptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventRegistrationFetchByPaymentIDRow{}
	for rows.Next() {
		var i EventRegistrationFetchByPaymentIDRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ClassEventID,
			&i.ClubID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventRegistrationFetchCart = `-- name: EventRegistrationFetchCart :many
SELECT e.id, e.name, e.thumbnail, SUM(ce.price) as total FROM event_registrations as er
INNER JOIN events as e ON e.id = er.event_id
INNER JOIN class_events as ce ON ce.id = er.class_event_id
INNER JOIN clubs as c ON c.id = er.club_id
WHERE er.status = 'pending' AND c.user_id = $1
GROUP BY e.id ORDER BY e.created_at DESC LIMIT $2 OFFSET $3
`

type EventRegistrationFetchCartParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type EventRegistrationFetchCartRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Thumbnail string    `json:"thumbnail"`
	Total     int64     `json:"total"`
}

func (q *Queries) EventRegistrationFetchCart(ctx context.Context, arg EventRegistrationFetchCartParams) ([]EventRegistrationFetchCartRow, error) {
	rows, err := q.db.QueryContext(ctx, eventRegistrationFetchCart, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventRegistrationFetchCartRow{}
	for rows.Next() {
		var i EventRegistrationFetchCartRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Thumbnail,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventRegistrationFetchClubByEventID = `-- name: EventRegistrationFetchClubByEventID :many
SELECT DISTINCT cl.id, cl.name FROM event_registrations as er
LEFT JOIN ranks as r ON r.event_registration_id = er.id
INNER JOIN clubs as cl ON cl.id = er.club_id
WHERE er.event_id = $1 and er.status = 'approved'
ORDER BY cl.name
`

type EventRegistrationFetchClubByEventIDRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) EventRegistrationFetchClubByEventID(ctx context.Context, eventID uuid.UUID) ([]EventRegistrationFetchClubByEventIDRow, error) {
	rows, err := q.db.QueryContext(ctx, eventRegistrationFetchClubByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventRegistrationFetchClubByEventIDRow{}
	for rows.Next() {
		var i EventRegistrationFetchClubByEventIDRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventRegistrationFetchOne = `-- name: EventRegistrationFetchOne :one
SELECT id, event_id, class_event_id, club_id, event_payment_receipt_id, status FROM event_registrations
WHERE id = $1
`

type EventRegistrationFetchOneRow struct {
	ID                    uuid.UUID               `json:"id"`
	EventID               uuid.UUID               `json:"event_id"`
	ClassEventID          uuid.UUID               `json:"class_event_id"`
	ClubID                uuid.UUID               `json:"club_id"`
	EventPaymentReceiptID uuid.UUID               `json:"event_payment_receipt_id"`
	Status                EventRegistrationStatus `json:"status"`
}

func (q *Queries) EventRegistrationFetchOne(ctx context.Context, id uuid.UUID) (EventRegistrationFetchOneRow, error) {
	row := q.db.QueryRowContext(ctx, eventRegistrationFetchOne, id)
	var i EventRegistrationFetchOneRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ClassEventID,
		&i.ClubID,
		&i.EventPaymentReceiptID,
		&i.Status,
	)
	return i, err
}

const eventRegistrationFetchPendingCron = `-- name: EventRegistrationFetchPendingCron :many
SELECT er.id FROM event_registrations as er
                      INNER JOIN events as e ON e.id = er.event_id
WHERE e.deadline <= $1 AND e.remark != ANY('{closed,ongoing,done}') AND er.status = 'pending'
`

func (q *Queries) EventRegistrationFetchPendingCron(ctx context.Context, deadline time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, eventRegistrationFetchPendingCron, deadline)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventRegistrationSetReject = `-- name: EventRegistrationSetReject :exec
UPDATE event_registrations SET status = 'rejected',
                               updated_at = NOW()
WHERE id = $1
`

func (q *Queries) EventRegistrationSetReject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, eventRegistrationSetReject, id)
	return err
}

const eventRegistrationUpdate = `-- name: EventRegistrationUpdate :exec
UPDATE event_registrations SET class_event_id = $1,
                               updated_at = NOW()
WHERE id = $2
`

type EventRegistrationUpdateParams struct {
	ClassEventID uuid.UUID `json:"class_event_id"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) EventRegistrationUpdate(ctx context.Context, arg EventRegistrationUpdateParams) error {
	_, err := q.db.ExecContext(ctx, eventRegistrationUpdate, arg.ClassEventID, arg.ID)
	return err
}

const eventRegistrationUpdateOnePaymentID = `-- name: EventRegistrationUpdateOnePaymentID :exec
UPDATE event_registrations SET event_payment_receipt_id = $1,
                               status = $2,
                               updated_at = NOW()
WHERE id = $3
`

type EventRegistrationUpdateOnePaymentIDParams struct {
	EventPaymentReceiptID uuid.UUID               `json:"event_payment_receipt_id"`
	Status                EventRegistrationStatus `json:"status"`
	ID                    uuid.UUID               `json:"id"`
}

func (q *Queries) EventRegistrationUpdateOnePaymentID(ctx context.Context, arg EventRegistrationUpdateOnePaymentIDParams) error {
	_, err := q.db.ExecContext(ctx, eventRegistrationUpdateOnePaymentID, arg.EventPaymentReceiptID, arg.Status, arg.ID)
	return err
}

const eventRegistrationUpdatePaymentID = `-- name: EventRegistrationUpdatePaymentID :exec
UPDATE event_registrations SET event_payment_receipt_id = $1,
                               status = $2,
                               updated_at = NOW()
WHERE event_payment_receipt_id = $1
`

type EventRegistrationUpdatePaymentIDParams struct {
	EventPaymentReceiptID uuid.UUID               `json:"event_payment_receipt_id"`
	Status                EventRegistrationStatus `json:"status"`
}

func (q *Queries) EventRegistrationUpdatePaymentID(ctx context.Context, arg EventRegistrationUpdatePaymentIDParams) error {
	_, err := q.db.ExecContext(ctx, eventRegistrationUpdatePaymentID, arg.EventPaymentReceiptID, arg.Status)
	return err
}

const eventRegistrationUpdateStatus = `-- name: EventRegistrationUpdateStatus :exec
UPDATE event_registrations SET status = $1,
                               updated_at = NOW()
WHERE id = $2
`

type EventRegistrationUpdateStatusParams struct {
	Status EventRegistrationStatus `json:"status"`
	ID     uuid.UUID               `json:"id"`
}

func (q *Queries) EventRegistrationUpdateStatus(ctx context.Context, arg EventRegistrationUpdateStatusParams) error {
	_, err := q.db.ExecContext(ctx, eventRegistrationUpdateStatus, arg.Status, arg.ID)
	return err
}
