// Code generated by sqlc. DO NOT EDIT.
// source: eventParticipant.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const eventParticipantCreate = `-- name: EventParticipantCreate :exec
INSERT INTO event_participants(event_registration_id, user_id, updated_at) VALUES ($1, $2, NOW())
`

type EventParticipantCreateParams struct {
	EventRegistrationID uuid.UUID `json:"event_registration_id"`
	UserID              uuid.UUID `json:"user_id"`
}

func (q *Queries) EventParticipantCreate(ctx context.Context, arg EventParticipantCreateParams) error {
	_, err := q.db.ExecContext(ctx, eventParticipantCreate, arg.EventRegistrationID, arg.UserID)
	return err
}

const eventParticipantFetchByEventIDAndClubID = `-- name: EventParticipantFetchByEventIDAndClubID :many
SELECT ep.id, ep.event_registration_id, ep.user_id, u.name, c.name as class_name FROM event_participants as ep
INNER JOIN event_registrations as er ON er.id = ep.event_registration_id
INNER JOIN class_events as ce ON ce.id = er.class_event_id
INNER JOIN classes as c ON c.id = ce.class_id
INNER JOIN users as u ON u.id = ep.user_id
WHERE er.event_id = $1 AND er.club_id = $2 AND er.status = 'approved'
ORDER BY u.name
`

type EventParticipantFetchByEventIDAndClubIDParams struct {
	EventID uuid.UUID `json:"event_id"`
	ClubID  uuid.UUID `json:"club_id"`
}

type EventParticipantFetchByEventIDAndClubIDRow struct {
	ID                  int64     `json:"id"`
	EventRegistrationID uuid.UUID `json:"event_registration_id"`
	UserID              uuid.UUID `json:"user_id"`
	Name                string    `json:"name"`
	ClassName           string    `json:"class_name"`
}

func (q *Queries) EventParticipantFetchByEventIDAndClubID(ctx context.Context, arg EventParticipantFetchByEventIDAndClubIDParams) ([]EventParticipantFetchByEventIDAndClubIDRow, error) {
	rows, err := q.db.QueryContext(ctx, eventParticipantFetchByEventIDAndClubID, arg.EventID, arg.ClubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventParticipantFetchByEventIDAndClubIDRow{}
	for rows.Next() {
		var i EventParticipantFetchByEventIDAndClubIDRow
		if err := rows.Scan(
			&i.ID,
			&i.EventRegistrationID,
			&i.UserID,
			&i.Name,
			&i.ClassName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventParticipantFetchByRegistrationID = `-- name: EventParticipantFetchByRegistrationID :many
SELECT ep.id, ep.event_registration_id, ep.user_id, u.name, c.name as class_name FROM event_participants as ep
INNER JOIN event_registrations as er ON er.id = ep.event_registration_id
INNER JOIN class_events as ce ON ce.id = er.class_event_id
INNER JOIN classes as c ON c.id = ce.class_id
INNER JOIN users as u ON u.id = ep.user_id
WHERE ep.event_registration_id = $1
`

type EventParticipantFetchByRegistrationIDRow struct {
	ID                  int64     `json:"id"`
	EventRegistrationID uuid.UUID `json:"event_registration_id"`
	UserID              uuid.UUID `json:"user_id"`
	Name                string    `json:"name"`
	ClassName           string    `json:"class_name"`
}

func (q *Queries) EventParticipantFetchByRegistrationID(ctx context.Context, eventRegistrationID uuid.UUID) ([]EventParticipantFetchByRegistrationIDRow, error) {
	rows, err := q.db.QueryContext(ctx, eventParticipantFetchByRegistrationID, eventRegistrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventParticipantFetchByRegistrationIDRow{}
	for rows.Next() {
		var i EventParticipantFetchByRegistrationIDRow
		if err := rows.Scan(
			&i.ID,
			&i.EventRegistrationID,
			&i.UserID,
			&i.Name,
			&i.ClassName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventParticipantFetchNameByRegistrationID = `-- name: EventParticipantFetchNameByRegistrationID :many
SELECT u.name FROM event_participants as ep
INNER JOIN users as u ON u.id = ep.user_id
WHERE ep.event_registration_id = $1
`

func (q *Queries) EventParticipantFetchNameByRegistrationID(ctx context.Context, eventRegistrationID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, eventParticipantFetchNameByRegistrationID, eventRegistrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
