// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: eventPayment.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const eventPaymentCheckOne = `-- name: EventPaymentCheckOne :one
SELECT ep.id FROM event_payment_receipts as ep
INNER JOIN event_registrations as er ON er.event_payment_receipt_id = ep.id
INNER JOIN clubs as c ON c.id = er.club_id
WHERE er.event_id = $1 AND ep.id = $2
`

type EventPaymentCheckOneParams struct {
	EventID uuid.UUID `json:"event_id"`
	ID      uuid.UUID `json:"id"`
}

func (q *Queries) EventPaymentCheckOne(ctx context.Context, arg EventPaymentCheckOneParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, eventPaymentCheckOne, arg.EventID, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const eventPaymentCreate = `-- name: EventPaymentCreate :one
INSERT INTO event_payment_receipts(unique_number, event_id, user_id ,payment_link, admin_id, total, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
RETURNING id
`

type EventPaymentCreateParams struct {
	UniqueNumber int16     `json:"unique_number"`
	EventID      uuid.UUID `json:"event_id"`
	UserID       uuid.UUID `json:"user_id"`
	PaymentLink  string    `json:"payment_link"`
	AdminID      uuid.UUID `json:"admin_id"`
	Total        int32     `json:"total"`
}

func (q *Queries) EventPaymentCreate(ctx context.Context, arg EventPaymentCreateParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, eventPaymentCreate,
		arg.UniqueNumber,
		arg.EventID,
		arg.UserID,
		arg.PaymentLink,
		arg.AdminID,
		arg.Total,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const eventPaymentFetchOne = `-- name: EventPaymentFetchOne :one
SELECT id, status, total, unique_number, created_at, event_id FROM event_payment_receipts WHERE id = $1 AND user_id = $2
`

type EventPaymentFetchOneParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type EventPaymentFetchOneRow struct {
	ID           uuid.UUID          `json:"id"`
	Status       EventReceiptStatus `json:"status"`
	Total        int32              `json:"total"`
	UniqueNumber int16              `json:"unique_number"`
	CreatedAt    time.Time          `json:"created_at"`
	EventID      uuid.UUID          `json:"event_id"`
}

func (q *Queries) EventPaymentFetchOne(ctx context.Context, arg EventPaymentFetchOneParams) (EventPaymentFetchOneRow, error) {
	row := q.db.QueryRowContext(ctx, eventPaymentFetchOne, arg.ID, arg.UserID)
	var i EventPaymentFetchOneRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Total,
		&i.UniqueNumber,
		&i.CreatedAt,
		&i.EventID,
	)
	return i, err
}

const eventPaymentFetchOneForAdmin = `-- name: EventPaymentFetchOneForAdmin :one
SELECT DISTINCT ep.id, ep.status, ep.total, ep.unique_number, ep.created_at, ep.payment_link,ep.event_id, c.name as club_name,
       u.name as owner, e.name as event_name
FROM event_payment_receipts as ep
INNER JOIN events as e ON e.id = ep.event_id
INNER JOIN event_registrations as er ON er.event_payment_receipt_id = ep.id
INNER JOIN clubs as c ON c.id = er.club_id
INNER JOIN users as u ON u.id = c.user_id
WHERE ep.id = $1
`

type EventPaymentFetchOneForAdminRow struct {
	ID           uuid.UUID          `json:"id"`
	Status       EventReceiptStatus `json:"status"`
	Total        int32              `json:"total"`
	UniqueNumber int16              `json:"unique_number"`
	CreatedAt    time.Time          `json:"created_at"`
	PaymentLink  string             `json:"payment_link"`
	EventID      uuid.UUID          `json:"event_id"`
	ClubName     string             `json:"club_name"`
	Owner        string             `json:"owner"`
	EventName    string             `json:"event_name"`
}

func (q *Queries) EventPaymentFetchOneForAdmin(ctx context.Context, id uuid.UUID) (EventPaymentFetchOneForAdminRow, error) {
	row := q.db.QueryRowContext(ctx, eventPaymentFetchOneForAdmin, id)
	var i EventPaymentFetchOneForAdminRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Total,
		&i.UniqueNumber,
		&i.CreatedAt,
		&i.PaymentLink,
		&i.EventID,
		&i.ClubName,
		&i.Owner,
		&i.EventName,
	)
	return i, err
}

const eventPaymentSumAll = `-- name: EventPaymentSumAll :one
SELECT SUM(c.price) FROM event_registrations AS er
INNER JOIN class_events AS ce ON ce.id = er.class_event_id
INNER JOIN classes as c ON c.id = ce.class_id
WHERE er.status = $1
`

func (q *Queries) EventPaymentSumAll(ctx context.Context, status EventRegistrationStatus) (int64, error) {
	row := q.db.QueryRowContext(ctx, eventPaymentSumAll, status)
	var sum int64
	err := row.Scan(&sum)
	return sum, err
}

const eventPaymentUpdate = `-- name: EventPaymentUpdate :exec
UPDATE event_payment_receipts SET status = $1,
                                  admin_id = $2,
                                  updated_at = NOW()
WHERE id = $3
`

type EventPaymentUpdateParams struct {
	Status  EventReceiptStatus `json:"status"`
	AdminID uuid.UUID          `json:"admin_id"`
	ID      uuid.UUID          `json:"id"`
}

func (q *Queries) EventPaymentUpdate(ctx context.Context, arg EventPaymentUpdateParams) error {
	_, err := q.db.ExecContext(ctx, eventPaymentUpdate, arg.Status, arg.AdminID, arg.ID)
	return err
}
