// Code generated by sqlc. DO NOT EDIT.
// source: eventPrivilege.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const eventPrivilegeCreate = `-- name: EventPrivilegeCreate :exec
INSERT INTO event_privileges (event_id, user_id, role, updated_at) VALUES ($1, $2, $3, NOW())
`

type EventPrivilegeCreateParams struct {
	EventID uuid.UUID `json:"event_id"`
	UserID  uuid.UUID `json:"user_id"`
	Role    EventRole `json:"role"`
}

func (q *Queries) EventPrivilegeCreate(ctx context.Context, arg EventPrivilegeCreateParams) error {
	_, err := q.db.ExecContext(ctx, eventPrivilegeCreate, arg.EventID, arg.UserID, arg.Role)
	return err
}

const eventPrivilegeDelete = `-- name: EventPrivilegeDelete :exec
DELETE FROM event_privileges WHERE event_id = $1 AND user_id = $2
`

type EventPrivilegeDeleteParams struct {
	EventID uuid.UUID `json:"event_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) EventPrivilegeDelete(ctx context.Context, arg EventPrivilegeDeleteParams) error {
	_, err := q.db.ExecContext(ctx, eventPrivilegeDelete, arg.EventID, arg.UserID)
	return err
}

const eventPrivilegeFetchAll = `-- name: EventPrivilegeFetchAll :many
SELECT ep.id, ep.role, ep.user_id, u.name FROM event_privileges as ep
INNER JOIN users as u ON u.id = ep.user_id
WHERE ep.event_id = $1
`

type EventPrivilegeFetchAllRow struct {
	ID     int64     `json:"id"`
	Role   EventRole `json:"role"`
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) EventPrivilegeFetchAll(ctx context.Context, eventID uuid.UUID) ([]EventPrivilegeFetchAllRow, error) {
	rows, err := q.db.QueryContext(ctx, eventPrivilegeFetchAll, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventPrivilegeFetchAllRow{}
	for rows.Next() {
		var i EventPrivilegeFetchAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.UserID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventPrivilegeFetchByEventID = `-- name: EventPrivilegeFetchByEventID :many
SELECT ep.id, ep.user_id, ep.role FROM event_privileges as ep
WHERE ep.event_id = $1
`

type EventPrivilegeFetchByEventIDRow struct {
	ID     int64     `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Role   EventRole `json:"role"`
}

func (q *Queries) EventPrivilegeFetchByEventID(ctx context.Context, eventID uuid.UUID) ([]EventPrivilegeFetchByEventIDRow, error) {
	rows, err := q.db.QueryContext(ctx, eventPrivilegeFetchByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventPrivilegeFetchByEventIDRow{}
	for rows.Next() {
		var i EventPrivilegeFetchByEventIDRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventPrivilegeFetchByUserID = `-- name: EventPrivilegeFetchByUserID :many
SELECT ep.id FROM event_privileges as ep
INNER JOIN events as e ON ep.event_id = e.id
WHERE e.deleted_at IS NULL AND ep.user_id = $1
`

func (q *Queries) EventPrivilegeFetchByUserID(ctx context.Context, userID uuid.UUID) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, eventPrivilegeFetchByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventPrivilegeFetchOne = `-- name: EventPrivilegeFetchOne :one
SELECT id, role FROM event_privileges WHERE event_id = $1 AND user_id = $2 LIMIT 1
`

type EventPrivilegeFetchOneParams struct {
	EventID uuid.UUID `json:"event_id"`
	UserID  uuid.UUID `json:"user_id"`
}

type EventPrivilegeFetchOneRow struct {
	ID   int64     `json:"id"`
	Role EventRole `json:"role"`
}

func (q *Queries) EventPrivilegeFetchOne(ctx context.Context, arg EventPrivilegeFetchOneParams) (EventPrivilegeFetchOneRow, error) {
	row := q.db.QueryRowContext(ctx, eventPrivilegeFetchOne, arg.EventID, arg.UserID)
	var i EventPrivilegeFetchOneRow
	err := row.Scan(&i.ID, &i.Role)
	return i, err
}

const eventPrivilegeUpdate = `-- name: EventPrivilegeUpdate :exec
UPDATE event_privileges SET role = $1,
                            updated_at = NOW()
WHERE user_id = $2 AND event_id = $3
`

type EventPrivilegeUpdateParams struct {
	Role    EventRole `json:"role"`
	UserID  uuid.UUID `json:"user_id"`
	EventID uuid.UUID `json:"event_id"`
}

func (q *Queries) EventPrivilegeUpdate(ctx context.Context, arg EventPrivilegeUpdateParams) error {
	_, err := q.db.ExecContext(ctx, eventPrivilegeUpdate, arg.Role, arg.UserID, arg.EventID)
	return err
}
