// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: eventBracket.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const eventBracketCheckOne = `-- name: EventBracketCheckOne :one
SELECT eb.id, eb.next_match_id, eb.match_order, eb.is_active, ce.score_lock FROM event_brackets as eb
INNER JOIN class_events as ce ON ce.id = eb.class_event_id
WHERE eb.id = $1
`

type EventBracketCheckOneRow struct {
	ID          uuid.UUID `json:"id"`
	NextMatchID uuid.UUID `json:"next_match_id"`
	MatchOrder  int16     `json:"match_order"`
	IsActive    int16     `json:"is_active"`
	ScoreLock   bool      `json:"score_lock"`
}

func (q *Queries) EventBracketCheckOne(ctx context.Context, id uuid.UUID) (EventBracketCheckOneRow, error) {
	row := q.db.QueryRowContext(ctx, eventBracketCheckOne, id)
	var i EventBracketCheckOneRow
	err := row.Scan(
		&i.ID,
		&i.NextMatchID,
		&i.MatchOrder,
		&i.IsActive,
		&i.ScoreLock,
	)
	return i, err
}

const eventBracketCreate = `-- name: EventBracketCreate :one
INSERT INTO event_brackets(event_id, class_event_id, event_turn, match_index, match_order, next_match_id, is_active,
                           status, updated_at)
VALUES($1, $2, $3, $4, $5, $6, $7, $8, NOW())
RETURNING id
`

type EventBracketCreateParams struct {
	EventID      uuid.UUID   `json:"event_id"`
	ClassEventID uuid.UUID   `json:"class_event_id"`
	EventTurn    int16       `json:"event_turn"`
	MatchIndex   int16       `json:"match_index"`
	MatchOrder   int16       `json:"match_order"`
	NextMatchID  uuid.UUID   `json:"next_match_id"`
	IsActive     int16       `json:"is_active"`
	Status       BracketType `json:"status"`
}

func (q *Queries) EventBracketCreate(ctx context.Context, arg EventBracketCreateParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, eventBracketCreate,
		arg.EventID,
		arg.ClassEventID,
		arg.EventTurn,
		arg.MatchIndex,
		arg.MatchOrder,
		arg.NextMatchID,
		arg.IsActive,
		arg.Status,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const eventBracketFetchByClassEventID = `-- name: EventBracketFetchByClassEventID :many
SELECT eb.id, eb.match_index, eb.match_order, eb.status, eb.event_turn, eb.is_active, COALESCE(ec.home_total,0),
       COALESCE(ec.away_total,0)
FROM event_brackets as eb
LEFT JOIN event_scores as ec ON ec.event_bracket_id = eb.id
WHERE eb.class_event_id = $1 AND eb.match_index = $2 ORDER BY eb.match_index DESC,eb.match_order
`

type EventBracketFetchByClassEventIDParams struct {
	ClassEventID uuid.UUID `json:"class_event_id"`
	MatchIndex   int16     `json:"match_index"`
}

type EventBracketFetchByClassEventIDRow struct {
	ID         uuid.UUID   `json:"id"`
	MatchIndex int16       `json:"match_index"`
	MatchOrder int16       `json:"match_order"`
	Status     BracketType `json:"status"`
	EventTurn  int16       `json:"event_turn"`
	IsActive   int16       `json:"is_active"`
	HomeTotal  int16       `json:"home_total"`
	AwayTotal  int16       `json:"away_total"`
}

func (q *Queries) EventBracketFetchByClassEventID(ctx context.Context, arg EventBracketFetchByClassEventIDParams) ([]EventBracketFetchByClassEventIDRow, error) {
	rows, err := q.db.QueryContext(ctx, eventBracketFetchByClassEventID, arg.ClassEventID, arg.MatchIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventBracketFetchByClassEventIDRow{}
	for rows.Next() {
		var i EventBracketFetchByClassEventIDRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchIndex,
			&i.MatchOrder,
			&i.Status,
			&i.EventTurn,
			&i.IsActive,
			&i.HomeTotal,
			&i.AwayTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventBracketFetchByClassEventIDAndMatchIndex = `-- name: EventBracketFetchByClassEventIDAndMatchIndex :many
SELECT eb.id, es.home_total, es.away_total FROM event_brackets AS eb
INNER JOIN event_scores AS es ON es.event_bracket_id = eb.id
WHERE eb.class_event_id = $1 AND eb.match_index = $2
`

type EventBracketFetchByClassEventIDAndMatchIndexParams struct {
	ClassEventID uuid.UUID `json:"class_event_id"`
	MatchIndex   int16     `json:"match_index"`
}

type EventBracketFetchByClassEventIDAndMatchIndexRow struct {
	ID        uuid.UUID `json:"id"`
	HomeTotal int16     `json:"home_total"`
	AwayTotal int16     `json:"away_total"`
}

func (q *Queries) EventBracketFetchByClassEventIDAndMatchIndex(ctx context.Context, arg EventBracketFetchByClassEventIDAndMatchIndexParams) ([]EventBracketFetchByClassEventIDAndMatchIndexRow, error) {
	rows, err := q.db.QueryContext(ctx, eventBracketFetchByClassEventIDAndMatchIndex, arg.ClassEventID, arg.MatchIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventBracketFetchByClassEventIDAndMatchIndexRow{}
	for rows.Next() {
		var i EventBracketFetchByClassEventIDAndMatchIndexRow
		if err := rows.Scan(&i.ID, &i.HomeTotal, &i.AwayTotal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventBracketFetchByClassEventStatusBattleAndMatchIndex = `-- name: EventBracketFetchByClassEventStatusBattleAndMatchIndex :many
SELECT id, match_index, status, event_turn FROM event_brackets
WHERE status = 'battle' AND class_event_id = $1 AND match_index = $2 ORDER BY match_order
`

type EventBracketFetchByClassEventStatusBattleAndMatchIndexParams struct {
	ClassEventID uuid.UUID `json:"class_event_id"`
	MatchIndex   int16     `json:"match_index"`
}

type EventBracketFetchByClassEventStatusBattleAndMatchIndexRow struct {
	ID         uuid.UUID   `json:"id"`
	MatchIndex int16       `json:"match_index"`
	Status     BracketType `json:"status"`
	EventTurn  int16       `json:"event_turn"`
}

func (q *Queries) EventBracketFetchByClassEventStatusBattleAndMatchIndex(ctx context.Context, arg EventBracketFetchByClassEventStatusBattleAndMatchIndexParams) ([]EventBracketFetchByClassEventStatusBattleAndMatchIndexRow, error) {
	rows, err := q.db.QueryContext(ctx, eventBracketFetchByClassEventStatusBattleAndMatchIndex, arg.ClassEventID, arg.MatchIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventBracketFetchByClassEventStatusBattleAndMatchIndexRow{}
	for rows.Next() {
		var i EventBracketFetchByClassEventStatusBattleAndMatchIndexRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchIndex,
			&i.Status,
			&i.EventTurn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventBracketFetchByClassEventStatusByeAndMatchIndex = `-- name: EventBracketFetchByClassEventStatusByeAndMatchIndex :many
SELECT id, match_index, match_order, status, event_turn, next_match_id FROM event_brackets
WHERE status = 'bye' AND class_event_id = $1 AND match_index = $2 ORDER BY match_order
`

type EventBracketFetchByClassEventStatusByeAndMatchIndexParams struct {
	ClassEventID uuid.UUID `json:"class_event_id"`
	MatchIndex   int16     `json:"match_index"`
}

type EventBracketFetchByClassEventStatusByeAndMatchIndexRow struct {
	ID          uuid.UUID   `json:"id"`
	MatchIndex  int16       `json:"match_index"`
	MatchOrder  int16       `json:"match_order"`
	Status      BracketType `json:"status"`
	EventTurn   int16       `json:"event_turn"`
	NextMatchID uuid.UUID   `json:"next_match_id"`
}

func (q *Queries) EventBracketFetchByClassEventStatusByeAndMatchIndex(ctx context.Context, arg EventBracketFetchByClassEventStatusByeAndMatchIndexParams) ([]EventBracketFetchByClassEventStatusByeAndMatchIndexRow, error) {
	rows, err := q.db.QueryContext(ctx, eventBracketFetchByClassEventStatusByeAndMatchIndex, arg.ClassEventID, arg.MatchIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventBracketFetchByClassEventStatusByeAndMatchIndexRow{}
	for rows.Next() {
		var i EventBracketFetchByClassEventStatusByeAndMatchIndexRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchIndex,
			&i.MatchOrder,
			&i.Status,
			&i.EventTurn,
			&i.NextMatchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventBracketFetchByMatchIndexAndClassID = `-- name: EventBracketFetchByMatchIndexAndClassID :many
SELECT id, match_index, match_order FROM event_brackets
WHERE match_index = $1 AND class_event_id = $2 ORDER BY match_index, match_order
`

type EventBracketFetchByMatchIndexAndClassIDParams struct {
	MatchIndex   int16     `json:"match_index"`
	ClassEventID uuid.UUID `json:"class_event_id"`
}

type EventBracketFetchByMatchIndexAndClassIDRow struct {
	ID         uuid.UUID `json:"id"`
	MatchIndex int16     `json:"match_index"`
	MatchOrder int16     `json:"match_order"`
}

func (q *Queries) EventBracketFetchByMatchIndexAndClassID(ctx context.Context, arg EventBracketFetchByMatchIndexAndClassIDParams) ([]EventBracketFetchByMatchIndexAndClassIDRow, error) {
	rows, err := q.db.QueryContext(ctx, eventBracketFetchByMatchIndexAndClassID, arg.MatchIndex, arg.ClassEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventBracketFetchByMatchIndexAndClassIDRow{}
	for rows.Next() {
		var i EventBracketFetchByMatchIndexAndClassIDRow
		if err := rows.Scan(&i.ID, &i.MatchIndex, &i.MatchOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eventBracketFetchOneByMatchIndexAndClassID = `-- name: EventBracketFetchOneByMatchIndexAndClassID :one
SELECT id, match_index, match_order FROM event_brackets
WHERE match_index = $1 AND class_event_id = $2 ORDER BY match_index, match_order
`

type EventBracketFetchOneByMatchIndexAndClassIDParams struct {
	MatchIndex   int16     `json:"match_index"`
	ClassEventID uuid.UUID `json:"class_event_id"`
}

type EventBracketFetchOneByMatchIndexAndClassIDRow struct {
	ID         uuid.UUID `json:"id"`
	MatchIndex int16     `json:"match_index"`
	MatchOrder int16     `json:"match_order"`
}

func (q *Queries) EventBracketFetchOneByMatchIndexAndClassID(ctx context.Context, arg EventBracketFetchOneByMatchIndexAndClassIDParams) (EventBracketFetchOneByMatchIndexAndClassIDRow, error) {
	row := q.db.QueryRowContext(ctx, eventBracketFetchOneByMatchIndexAndClassID, arg.MatchIndex, arg.ClassEventID)
	var i EventBracketFetchOneByMatchIndexAndClassIDRow
	err := row.Scan(&i.ID, &i.MatchIndex, &i.MatchOrder)
	return i, err
}

const eventBracketUpdateEventTurnByID = `-- name: EventBracketUpdateEventTurnByID :exec
UPDATE event_brackets SET event_turn = $1,
                          updated_at = NOW()
WHERE id = $2
`

type EventBracketUpdateEventTurnByIDParams struct {
	EventTurn int16     `json:"event_turn"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) EventBracketUpdateEventTurnByID(ctx context.Context, arg EventBracketUpdateEventTurnByIDParams) error {
	_, err := q.db.ExecContext(ctx, eventBracketUpdateEventTurnByID, arg.EventTurn, arg.ID)
	return err
}

const eventBracketUpdateNextMatch = `-- name: EventBracketUpdateNextMatch :exec
UPDATE event_brackets SET next_match_id = $1,
                          updated_at = NOW()
WHERE class_event_id = $2 AND match_index = $3 AND match_order = $4
`

type EventBracketUpdateNextMatchParams struct {
	NextMatchID  uuid.UUID `json:"next_match_id"`
	ClassEventID uuid.UUID `json:"class_event_id"`
	MatchIndex   int16     `json:"match_index"`
	MatchOrder   int16     `json:"match_order"`
}

func (q *Queries) EventBracketUpdateNextMatch(ctx context.Context, arg EventBracketUpdateNextMatchParams) error {
	_, err := q.db.ExecContext(ctx, eventBracketUpdateNextMatch,
		arg.NextMatchID,
		arg.ClassEventID,
		arg.MatchIndex,
		arg.MatchOrder,
	)
	return err
}

const eventBracketUpdateStatus = `-- name: EventBracketUpdateStatus :exec
UPDATE event_brackets SET status = $1,
                          is_active = $2,
                          updated_at = NOW()
WHERE id = $3
`

type EventBracketUpdateStatusParams struct {
	Status   BracketType `json:"status"`
	IsActive int16       `json:"is_active"`
	ID       uuid.UUID   `json:"id"`
}

func (q *Queries) EventBracketUpdateStatus(ctx context.Context, arg EventBracketUpdateStatusParams) error {
	_, err := q.db.ExecContext(ctx, eventBracketUpdateStatus, arg.Status, arg.IsActive, arg.ID)
	return err
}
