// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: eventBracketScore.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const eventScoreCheckOneByBracketID = `-- name: EventScoreCheckOneByBracketID :one
SELECT id FROM event_scores WHERE event_bracket_id = $1
`

func (q *Queries) EventScoreCheckOneByBracketID(ctx context.Context, eventBracketID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, eventScoreCheckOneByBracketID, eventBracketID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const eventScoreCreate = `-- name: EventScoreCreate :exec
INSERT INTO event_scores(event_bracket_id, home_round1, home_round2, home_round3, home_extra, home_total,
                         away_round1, away_round2, away_round3, away_extra, away_total, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW())
`

type EventScoreCreateParams struct {
	EventBracketID uuid.UUID `json:"event_bracket_id"`
	HomeRound1     int16     `json:"home_round1"`
	HomeRound2     int16     `json:"home_round2"`
	HomeRound3     int16     `json:"home_round3"`
	HomeExtra      int16     `json:"home_extra"`
	HomeTotal      int16     `json:"home_total"`
	AwayRound1     int16     `json:"away_round1"`
	AwayRound2     int16     `json:"away_round2"`
	AwayRound3     int16     `json:"away_round3"`
	AwayExtra      int16     `json:"away_extra"`
	AwayTotal      int16     `json:"away_total"`
}

func (q *Queries) EventScoreCreate(ctx context.Context, arg EventScoreCreateParams) error {
	_, err := q.db.ExecContext(ctx, eventScoreCreate,
		arg.EventBracketID,
		arg.HomeRound1,
		arg.HomeRound2,
		arg.HomeRound3,
		arg.HomeExtra,
		arg.HomeTotal,
		arg.AwayRound1,
		arg.AwayRound2,
		arg.AwayRound3,
		arg.AwayExtra,
		arg.AwayTotal,
	)
	return err
}

const eventScoreFetchAwayByBracketID = `-- name: EventScoreFetchAwayByBracketID :one
SELECT id, away_round1, away_round2, away_round3, away_extra, away_total
FROM event_scores
WHERE event_bracket_id = $1
`

type EventScoreFetchAwayByBracketIDRow struct {
	ID         uuid.UUID `json:"id"`
	AwayRound1 int16     `json:"away_round1"`
	AwayRound2 int16     `json:"away_round2"`
	AwayRound3 int16     `json:"away_round3"`
	AwayExtra  int16     `json:"away_extra"`
	AwayTotal  int16     `json:"away_total"`
}

func (q *Queries) EventScoreFetchAwayByBracketID(ctx context.Context, eventBracketID uuid.UUID) (EventScoreFetchAwayByBracketIDRow, error) {
	row := q.db.QueryRowContext(ctx, eventScoreFetchAwayByBracketID, eventBracketID)
	var i EventScoreFetchAwayByBracketIDRow
	err := row.Scan(
		&i.ID,
		&i.AwayRound1,
		&i.AwayRound2,
		&i.AwayRound3,
		&i.AwayExtra,
		&i.AwayTotal,
	)
	return i, err
}

const eventScoreFetchHomeByBracketID = `-- name: EventScoreFetchHomeByBracketID :one
SELECT id, home_round1, home_round2, home_round3, home_extra, home_total
FROM event_scores
WHERE event_bracket_id = $1
`

type EventScoreFetchHomeByBracketIDRow struct {
	ID         uuid.UUID `json:"id"`
	HomeRound1 int16     `json:"home_round1"`
	HomeRound2 int16     `json:"home_round2"`
	HomeRound3 int16     `json:"home_round3"`
	HomeExtra  int16     `json:"home_extra"`
	HomeTotal  int16     `json:"home_total"`
}

func (q *Queries) EventScoreFetchHomeByBracketID(ctx context.Context, eventBracketID uuid.UUID) (EventScoreFetchHomeByBracketIDRow, error) {
	row := q.db.QueryRowContext(ctx, eventScoreFetchHomeByBracketID, eventBracketID)
	var i EventScoreFetchHomeByBracketIDRow
	err := row.Scan(
		&i.ID,
		&i.HomeRound1,
		&i.HomeRound2,
		&i.HomeRound3,
		&i.HomeExtra,
		&i.HomeTotal,
	)
	return i, err
}

const eventScoreFetchOneByBracketID = `-- name: EventScoreFetchOneByBracketID :one
SELECT id, home_round1, home_round2, home_round3, home_extra, home_total,
       away_round1, away_round2, away_round3, away_extra, away_total
FROM event_scores
WHERE event_bracket_id = $1
`

type EventScoreFetchOneByBracketIDRow struct {
	ID         uuid.UUID `json:"id"`
	HomeRound1 int16     `json:"home_round1"`
	HomeRound2 int16     `json:"home_round2"`
	HomeRound3 int16     `json:"home_round3"`
	HomeExtra  int16     `json:"home_extra"`
	HomeTotal  int16     `json:"home_total"`
	AwayRound1 int16     `json:"away_round1"`
	AwayRound2 int16     `json:"away_round2"`
	AwayRound3 int16     `json:"away_round3"`
	AwayExtra  int16     `json:"away_extra"`
	AwayTotal  int16     `json:"away_total"`
}

func (q *Queries) EventScoreFetchOneByBracketID(ctx context.Context, eventBracketID uuid.UUID) (EventScoreFetchOneByBracketIDRow, error) {
	row := q.db.QueryRowContext(ctx, eventScoreFetchOneByBracketID, eventBracketID)
	var i EventScoreFetchOneByBracketIDRow
	err := row.Scan(
		&i.ID,
		&i.HomeRound1,
		&i.HomeRound2,
		&i.HomeRound3,
		&i.HomeExtra,
		&i.HomeTotal,
		&i.AwayRound1,
		&i.AwayRound2,
		&i.AwayRound3,
		&i.AwayExtra,
		&i.AwayTotal,
	)
	return i, err
}

const eventScoreUpdate = `-- name: EventScoreUpdate :exec
UPDATE event_scores SET home_round1 = $1,
                        home_round2 = $2,
                        home_round3 = $3,
                        home_extra = $4,
                        home_total = $5,
                        away_round1 = $6,
                        away_round2 = $7,
                        away_round3 = $8,
                        away_extra = $9,
                        away_total = $10,
                        updated_at = NOW()
WHERE event_bracket_id = $11
`

type EventScoreUpdateParams struct {
	HomeRound1     int16     `json:"home_round1"`
	HomeRound2     int16     `json:"home_round2"`
	HomeRound3     int16     `json:"home_round3"`
	HomeExtra      int16     `json:"home_extra"`
	HomeTotal      int16     `json:"home_total"`
	AwayRound1     int16     `json:"away_round1"`
	AwayRound2     int16     `json:"away_round2"`
	AwayRound3     int16     `json:"away_round3"`
	AwayExtra      int16     `json:"away_extra"`
	AwayTotal      int16     `json:"away_total"`
	EventBracketID uuid.UUID `json:"event_bracket_id"`
}

func (q *Queries) EventScoreUpdate(ctx context.Context, arg EventScoreUpdateParams) error {
	_, err := q.db.ExecContext(ctx, eventScoreUpdate,
		arg.HomeRound1,
		arg.HomeRound2,
		arg.HomeRound3,
		arg.HomeExtra,
		arg.HomeTotal,
		arg.AwayRound1,
		arg.AwayRound2,
		arg.AwayRound3,
		arg.AwayExtra,
		arg.AwayTotal,
		arg.EventBracketID,
	)
	return err
}
