// Code generated by sqlc. DO NOT EDIT.
// source: login_detail.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const loginDetailCount = `-- name: LoginDetailCount :one
SELECT COUNT(id) FROM login_details
`

func (q *Queries) LoginDetailCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, loginDetailCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const loginDetailCreate = `-- name: LoginDetailCreate :exec
INSERT INTO login_details(user_id, updated_at) VALUES ($1, NOW())
`

func (q *Queries) LoginDetailCreate(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, loginDetailCreate, userID)
	return err
}

const loginDetailFetchAll = `-- name: LoginDetailFetchAll :many
SELECT u.name, ld.created_at as last_login FROM login_details as ld
INNER JOIN users as u ON u.id = ld.user_id
ORDER BY last_login DESC
LIMIT $1 OFFSET $2
`

type LoginDetailFetchAllParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type LoginDetailFetchAllRow struct {
	Name      string    `json:"name"`
	LastLogin time.Time `json:"last_login"`
}

func (q *Queries) LoginDetailFetchAll(ctx context.Context, arg LoginDetailFetchAllParams) ([]LoginDetailFetchAllRow, error) {
	rows, err := q.db.QueryContext(ctx, loginDetailFetchAll, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoginDetailFetchAllRow{}
	for rows.Next() {
		var i LoginDetailFetchAllRow
		if err := rows.Scan(&i.Name, &i.LastLogin); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loginDetailLastRecord = `-- name: LoginDetailLastRecord :one
SELECT u.name, ld.created_at as last_login FROM login_details as ld
INNER JOIN users as u ON u.id = ld.user_id
ORDER BY ld.created_at DESC
`

type LoginDetailLastRecordRow struct {
	Name      string    `json:"name"`
	LastLogin time.Time `json:"last_login"`
}

func (q *Queries) LoginDetailLastRecord(ctx context.Context) (LoginDetailLastRecordRow, error) {
	row := q.db.QueryRowContext(ctx, loginDetailLastRecord)
	var i LoginDetailLastRecordRow
	err := row.Scan(&i.Name, &i.LastLogin)
	return i, err
}
