// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type AccountType string

const (
	AccountTypeManual   AccountType = "manual"
	AccountTypeFacebook AccountType = "facebook"
	AccountTypeGoogle   AccountType = "google"
)

func (e *AccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountType(s)
	case string:
		*e = AccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountType: %T", src)
	}
	return nil
}

type NullAccountType struct {
	AccountType AccountType `json:"account_type"`
	Valid       bool        `json:"valid"` // Valid is true if AccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.AccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountType), nil
}

type PrivilegeType string

const (
	PrivilegeTypeMain        PrivilegeType = "main"
	PrivilegeTypeCompetition PrivilegeType = "competition"
)

func (e *PrivilegeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PrivilegeType(s)
	case string:
		*e = PrivilegeType(s)
	default:
		return fmt.Errorf("unsupported scan type for PrivilegeType: %T", src)
	}
	return nil
}

type NullPrivilegeType struct {
	PrivilegeType PrivilegeType `json:"privilege_type"`
	Valid         bool          `json:"valid"` // Valid is true if PrivilegeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPrivilegeType) Scan(value interface{}) error {
	if value == nil {
		ns.PrivilegeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PrivilegeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPrivilegeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PrivilegeType), nil
}

type Role string

const (
	RoleAdmin Role = "admin"
	RoleUser  Role = "user"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role `json:"role"`
	Valid bool `json:"valid"` // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type Account struct {
	ID        int64        `json:"id"`
	Type      AccountType  `json:"type"`
	Username  string       `json:"username"`
	Password  string       `json:"password"`
	UserID    uuid.UUID    `json:"user_id"`
	Status    bool         `json:"status"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Club struct {
	ID        uuid.UUID    `json:"id"`
	Name      string       `json:"name"`
	Logo      string       `json:"logo"`
	Phone     string       `json:"phone"`
	ShortName string       `json:"short_name"`
	UserID    uuid.UUID    `json:"user_id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type ClubParticipant struct {
	ID           int64        `json:"id"`
	ClubID       uuid.UUID    `json:"club_id"`
	UserID       uuid.UUID    `json:"user_id"`
	SportID      uuid.UUID    `json:"sport_id"`
	ClubApproval sql.NullBool `json:"club_approval"`
	UserApproval sql.NullBool `json:"user_approval"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
}

type ClubSport struct {
	ID        int64        `json:"id"`
	ClubID    uuid.UUID    `json:"club_id"`
	SportID   uuid.UUID    `json:"sport_id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Document struct {
	ID                    int64        `json:"id"`
	UserID                uuid.UUID    `json:"user_id"`
	BirthCertificate      string       `json:"birth_certificate"`
	FamilyCard            string       `json:"family_card"`
	UserIdentity          string       `json:"user_identity"`
	BeltCertificate       string       `json:"belt_certificate"`
	ElementaryCertificate string       `json:"elementary_certificate"`
	MiddleCertificate     string       `json:"middle_certificate"`
	HighCertificate       string       `json:"high_certificate"`
	BachelorCertificate   string       `json:"bachelor_certificate"`
	MasterCertificate     string       `json:"master_certificate"`
	CreatedAt             time.Time    `json:"created_at"`
	UpdatedAt             sql.NullTime `json:"updated_at"`
}

type LoginDetail struct {
	ID        int64        `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Privilege struct {
	ID          uuid.UUID     `json:"id"`
	Name        string        `json:"name"`
	Type        PrivilegeType `json:"type"`
	Description string        `json:"description"`
	CreatedAt   sql.NullTime  `json:"created_at"`
	UpdatedAt   sql.NullTime  `json:"updated_at"`
}

type PrivilegeUser struct {
	ID          int64        `json:"id"`
	PrivilegeID uuid.UUID    `json:"privilege_id"`
	UserID      uuid.UUID    `json:"user_id"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
}

type Test struct {
	ID        int32        `json:"id"`
	Uuid      uuid.UUID    `json:"uuid"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type User struct {
	ID             uuid.UUID    `json:"id"`
	Name           string       `json:"name"`
	BornAt         string       `json:"born_at"`
	BornOn         sql.NullTime `json:"born_on"`
	IdentityNumber string       `json:"identity_number"`
	Phone          string       `json:"phone"`
	Photo          string       `json:"photo"`
	Role           Role         `json:"role"`
	Gender         string       `json:"gender"`
	About          string       `json:"about"`
	Status         bool         `json:"status"`
	CanParticipate bool         `json:"can_participate"`
	CreatedAt      time.Time    `json:"created_at"`
	UpdatedAt      sql.NullTime `json:"updated_at"`
}

type SportType string

const (
	SportTypeESport SportType = "e-sport"
	SportTypeSport  SportType = "sport"
)

type AccomplishmentLevel string

const (
	AccomplishmentLevelRegion        AccomplishmentLevel = "region"
	AccomplishmentLevelProvince      AccomplishmentLevel = "province"
	AccomplishmentLevelNational      AccomplishmentLevel = "national"
	AccomplishmentLevelInternational AccomplishmentLevel = "international"
	AccomplishmentLevelOthers        AccomplishmentLevel = "others"
)
