// Code generated by sqlc. DO NOT EDIT.
// source: orderBracket.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const orderBracketCheckOne = `-- name: OrderBracketCheckOne :one
SELECT ob.id, ob.order_by, ce.score_lock FROM order_brackets as ob
INNER JOIN class_events as ce ON ce.id = ob.class_event_id
WHERE ob.id = $1
`

type OrderBracketCheckOneRow struct {
	ID        uuid.UUID `json:"id"`
	OrderBy   int16     `json:"order_by"`
	ScoreLock bool      `json:"score_lock"`
}

func (q *Queries) OrderBracketCheckOne(ctx context.Context, id uuid.UUID) (OrderBracketCheckOneRow, error) {
	row := q.db.QueryRowContext(ctx, orderBracketCheckOne, id)
	var i OrderBracketCheckOneRow
	err := row.Scan(&i.ID, &i.OrderBy, &i.ScoreLock)
	return i, err
}

const orderBracketCreate = `-- name: OrderBracketCreate :exec
INSERT INTO order_brackets(event_id, class_event_id, club_id, event_registration_id, updated_at)
VALUES ($1, $2, $3, $4, NOW())
`

type OrderBracketCreateParams struct {
	EventID             uuid.UUID `json:"event_id"`
	ClassEventID        uuid.UUID `json:"class_event_id"`
	ClubID              uuid.UUID `json:"club_id"`
	EventRegistrationID uuid.UUID `json:"event_registration_id"`
}

func (q *Queries) OrderBracketCreate(ctx context.Context, arg OrderBracketCreateParams) error {
	_, err := q.db.ExecContext(ctx, orderBracketCreate,
		arg.EventID,
		arg.ClassEventID,
		arg.ClubID,
		arg.EventRegistrationID,
	)
	return err
}

const orderBracketDeleteByClassEventID = `-- name: OrderBracketDeleteByClassEventID :exec
DELETE FROM order_brackets WHERE class_event_id = $1
`

func (q *Queries) OrderBracketDeleteByClassEventID(ctx context.Context, classEventID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, orderBracketDeleteByClassEventID, classEventID)
	return err
}

const orderBracketFetchByClassEventID = `-- name: OrderBracketFetchByClassEventID :many
SELECT ob.id, ob.rank, ob.order_by,
       array(SELECT u.name FROM event_participants as ep
           INNER JOIN users as u ON u.id = ep.user_id
           WHERE ep.event_registration_id = ob.event_registration_id
        ) as participants, c.name as club_name
FROM order_brackets as ob
INNER JOIN clubs as c ON c.id = ob.club_id
WHERE ob.class_event_id = $1 ORDER BY ob.order_by
`

type OrderBracketFetchByClassEventIDRow struct {
	ID           uuid.UUID   `json:"id"`
	Rank         int16       `json:"rank"`
	OrderBy      int16       `json:"order_by"`
	Participants interface{} `json:"participants"`
	ClubName     string      `json:"club_name"`
}

func (q *Queries) OrderBracketFetchByClassEventID(ctx context.Context, classEventID uuid.UUID) ([]OrderBracketFetchByClassEventIDRow, error) {
	rows, err := q.db.QueryContext(ctx, orderBracketFetchByClassEventID, classEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderBracketFetchByClassEventIDRow{}
	for rows.Next() {
		var i OrderBracketFetchByClassEventIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Rank,
			&i.OrderBy,
			&i.Participants,
			&i.ClubName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orderBracketFetchByClassEventIDAndOrderByScore = `-- name: OrderBracketFetchByClassEventIDAndOrderByScore :many
SELECT ob.id, ob.event_registration_id, ob.class_event_id, ob.club_id, os.total
FROM order_brackets as ob
INNER JOIN order_scores as os ON os.order_bracket_id = ob.id
WHERE ob.class_event_id = $1
ORDER BY os.total DESC
`

type OrderBracketFetchByClassEventIDAndOrderByScoreRow struct {
	ID                  uuid.UUID `json:"id"`
	EventRegistrationID uuid.UUID `json:"event_registration_id"`
	ClassEventID        uuid.UUID `json:"class_event_id"`
	ClubID              uuid.UUID `json:"club_id"`
	Total               int16     `json:"total"`
}

func (q *Queries) OrderBracketFetchByClassEventIDAndOrderByScore(ctx context.Context, classEventID uuid.UUID) ([]OrderBracketFetchByClassEventIDAndOrderByScoreRow, error) {
	rows, err := q.db.QueryContext(ctx, orderBracketFetchByClassEventIDAndOrderByScore, classEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderBracketFetchByClassEventIDAndOrderByScoreRow{}
	for rows.Next() {
		var i OrderBracketFetchByClassEventIDAndOrderByScoreRow
		if err := rows.Scan(
			&i.ID,
			&i.EventRegistrationID,
			&i.ClassEventID,
			&i.ClubID,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orderBracketUpdateOrderBy = `-- name: OrderBracketUpdateOrderBy :exec
UPDATE order_brackets SET order_by = $1,
                          updated_at = NOW()
WHERE event_registration_id = $2
`

type OrderBracketUpdateOrderByParams struct {
	OrderBy             int16     `json:"order_by"`
	EventRegistrationID uuid.UUID `json:"event_registration_id"`
}

func (q *Queries) OrderBracketUpdateOrderBy(ctx context.Context, arg OrderBracketUpdateOrderByParams) error {
	_, err := q.db.ExecContext(ctx, orderBracketUpdateOrderBy, arg.OrderBy, arg.EventRegistrationID)
	return err
}

const orderBracketUpdateRank = `-- name: OrderBracketUpdateRank :exec
UPDATE order_brackets SET rank = $1,
                          updated_at = NOW()
WHERE id = $2
`

type OrderBracketUpdateRankParams struct {
	Rank int16     `json:"rank"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) OrderBracketUpdateRank(ctx context.Context, arg OrderBracketUpdateRankParams) error {
	_, err := q.db.ExecContext(ctx, orderBracketUpdateRank, arg.Rank, arg.ID)
	return err
}
