// Code generated by sqlc. DO NOT EDIT.
// source: orderScore.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const orderScoreCheckOneByBracketID = `-- name: OrderScoreCheckOneByBracketID :one
SELECT id FROM order_scores WHERE order_bracket_id = $1
`

func (q *Queries) OrderScoreCheckOneByBracketID(ctx context.Context, orderBracketID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, orderScoreCheckOneByBracketID, orderBracketID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const orderScoreCreate = `-- name: OrderScoreCreate :exec
INSERT INTO order_scores(order_bracket_id, round1, round2, round3, extra, total, updated_at)
VALUES($1, $2, $3, $4, $5, $6, NOW())
`

type OrderScoreCreateParams struct {
	OrderBracketID uuid.UUID `json:"order_bracket_id"`
	Round1         int16     `json:"round1"`
	Round2         int16     `json:"round2"`
	Round3         int16     `json:"round3"`
	Extra          int16     `json:"extra"`
	Total          int16     `json:"total"`
}

func (q *Queries) OrderScoreCreate(ctx context.Context, arg OrderScoreCreateParams) error {
	_, err := q.db.ExecContext(ctx, orderScoreCreate,
		arg.OrderBracketID,
		arg.Round1,
		arg.Round2,
		arg.Round3,
		arg.Extra,
		arg.Total,
	)
	return err
}

const orderScoreFetchOneByBracketID = `-- name: OrderScoreFetchOneByBracketID :one
SELECT id, round1, round2, round3, extra, total FROM order_scores WHERE order_bracket_id = $1
`

type OrderScoreFetchOneByBracketIDRow struct {
	ID     uuid.UUID `json:"id"`
	Round1 int16     `json:"round1"`
	Round2 int16     `json:"round2"`
	Round3 int16     `json:"round3"`
	Extra  int16     `json:"extra"`
	Total  int16     `json:"total"`
}

func (q *Queries) OrderScoreFetchOneByBracketID(ctx context.Context, orderBracketID uuid.UUID) (OrderScoreFetchOneByBracketIDRow, error) {
	row := q.db.QueryRowContext(ctx, orderScoreFetchOneByBracketID, orderBracketID)
	var i OrderScoreFetchOneByBracketIDRow
	err := row.Scan(
		&i.ID,
		&i.Round1,
		&i.Round2,
		&i.Round3,
		&i.Extra,
		&i.Total,
	)
	return i, err
}

const orderScoreUpdate = `-- name: OrderScoreUpdate :exec
UPDATE order_scores SET round1 = $1,
                        round2 = $2,
                        round3 = $3,
                        extra = $4,
                        total = $5,
                        updated_at = NOW()
WHERE order_bracket_id = $6
`

type OrderScoreUpdateParams struct {
	Round1         int16     `json:"round1"`
	Round2         int16     `json:"round2"`
	Round3         int16     `json:"round3"`
	Extra          int16     `json:"extra"`
	Total          int16     `json:"total"`
	OrderBracketID uuid.UUID `json:"order_bracket_id"`
}

func (q *Queries) OrderScoreUpdate(ctx context.Context, arg OrderScoreUpdateParams) error {
	_, err := q.db.ExecContext(ctx, orderScoreUpdate,
		arg.Round1,
		arg.Round2,
		arg.Round3,
		arg.Extra,
		arg.Total,
		arg.OrderBracketID,
	)
	return err
}
