// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: privilege.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const privilegeFetchByUserID = `-- name: PrivilegeFetchByUserID :many
SELECT privileges.name FROM privileges
                                               INNER JOIN privilege_user ON privileges.id = privilege_user.privilege_id
                                               INNER JOIN users ON privilege_user.user_id = users.id
WHERE users.id = $1
`

func (q *Queries) PrivilegeFetchByUserID(ctx context.Context, id uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, privilegeFetchByUserID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const privilegeFetchOneByUserID = `-- name: PrivilegeFetchOneByUserID :one
SELECT privileges.id, privileges.name FROM privileges
INNER JOIN privilege_user ON privileges.id = privilege_user.privilege_id
INNER JOIN users ON privilege_user.user_id = users.id
WHERE users.id = $1 AND privileges.name = $2 AND privileges.type = $3 LIMIT 1
`

type PrivilegeFetchOneByUserIDParams struct {
	ID   uuid.UUID     `json:"id"`
	Name string        `json:"name"`
	Type PrivilegeType `json:"type"`
}

type PrivilegeFetchOneByUserIDRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) PrivilegeFetchOneByUserID(ctx context.Context, arg PrivilegeFetchOneByUserIDParams) (PrivilegeFetchOneByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, privilegeFetchOneByUserID, arg.ID, arg.Name, arg.Type)
	var i PrivilegeFetchOneByUserIDRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
