// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: rank.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const rankClubFetchByEventID = `-- name: RankClubFetchByEventID :many
SELECT r.club_id, c.name AS club_name,
       COUNT(*) FILTER (WHERE r.rank = 1) AS rank1,
       COUNT(*) FILTER (WHERE r.rank = 2) AS rank2,
       COUNT(*) FILTER (WHERE r.rank = 3 OR r.rank = 4) AS rank3,
       SUM(r.point) as total_point
FROM ranks as r
         INNER JOIN clubs as c ON c.id = r.club_id
WHERE r.event_id = $1
GROUP BY r.club_id, c.name
ORDER BY rank1 DESC, rank2 DESC, rank3 desc, total_point DESC
`

type RankClubFetchByEventIDRow struct {
	ClubID     uuid.UUID `json:"club_id"`
	ClubName   string    `json:"club_name"`
	Rank1      int64     `json:"rank1"`
	Rank2      int64     `json:"rank2"`
	Rank3      int64     `json:"rank3"`
	TotalPoint int64     `json:"total_point"`
}

func (q *Queries) RankClubFetchByEventID(ctx context.Context, eventID uuid.UUID) ([]RankClubFetchByEventIDRow, error) {
	rows, err := q.db.QueryContext(ctx, rankClubFetchByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RankClubFetchByEventIDRow{}
	for rows.Next() {
		var i RankClubFetchByEventIDRow
		if err := rows.Scan(
			&i.ClubID,
			&i.ClubName,
			&i.Rank1,
			&i.Rank2,
			&i.Rank3,
			&i.TotalPoint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rankCountAllPointUser = `-- name: RankCountAllPointUser :one
SELECT COUNT(*) FROM (SELECT u.id, u.name, COALESCE(SUM(r.point),0) as point FROM ranks as r
INNER JOIN event_registrations as er ON er.id = r.event_registration_id
INNER JOIN event_participants as ep ON ep.event_registration_id = er.id
INNER JOIN users as u ON u.id = ep.user_id
GROUP BY u.id, r.club_id
ORDER BY point DESC) as total
`

func (q *Queries) RankCountAllPointUser(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, rankCountAllPointUser)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const rankCreate = `-- name: RankCreate :exec
INSERT INTO ranks(club_id, event_id, class_event_id, event_registration_id, sport_id, rank, point, updated_at)
VALUES($1, $2, $3, $4, $5, $6, $7, NOW())
`

type RankCreateParams struct {
	ClubID              uuid.UUID `json:"club_id"`
	EventID             uuid.UUID `json:"event_id"`
	ClassEventID        uuid.UUID `json:"class_event_id"`
	EventRegistrationID uuid.UUID `json:"event_registration_id"`
	SportID             uuid.UUID `json:"sport_id"`
	Rank                int16     `json:"rank"`
	Point               int32     `json:"point"`
}

func (q *Queries) RankCreate(ctx context.Context, arg RankCreateParams) error {
	_, err := q.db.ExecContext(ctx, rankCreate,
		arg.ClubID,
		arg.EventID,
		arg.ClassEventID,
		arg.EventRegistrationID,
		arg.SportID,
		arg.Rank,
		arg.Point,
	)
	return err
}

const rankFetchAllPointByClubID = `-- name: RankFetchAllPointByClubID :many
SELECT u.id, u.name, COALESCE(SUM(r.point),0) as point FROM ranks as r
INNER JOIN event_registrations as er ON er.id = r.event_registration_id
INNER JOIN event_participants as ep ON ep.event_registration_id = er.id
INNER JOIN users as u ON u.id = ep.user_id
GROUP BY u.id, r.club_id
HAVING r.club_id = $1
`

type RankFetchAllPointByClubIDRow struct {
	ID    uuid.UUID   `json:"id"`
	Name  string      `json:"name"`
	Point interface{} `json:"point"`
}

func (q *Queries) RankFetchAllPointByClubID(ctx context.Context, clubID uuid.UUID) ([]RankFetchAllPointByClubIDRow, error) {
	rows, err := q.db.QueryContext(ctx, rankFetchAllPointByClubID, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RankFetchAllPointByClubIDRow{}
	for rows.Next() {
		var i RankFetchAllPointByClubIDRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Point); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rankFetchPointByClubID = `-- name: RankFetchPointByClubID :one
SELECT SUM(point) as total FROM ranks WHERE club_id = $1
`

func (q *Queries) RankFetchPointByClubID(ctx context.Context, clubID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, rankFetchPointByClubID, clubID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const rankFetchPointByClubIDAndUserID = `-- name: RankFetchPointByClubIDAndUserID :one
SELECT SUM(r.point) as total FROM ranks as r
INNER JOIN event_registrations as er ON er.id = r.event_registration_id
INNER JOIN event_participants as ep ON ep.event_registration_id = er.id
WHERE er.club_id = $1 AND ep.user_id = $2
`

type RankFetchPointByClubIDAndUserIDParams struct {
	ClubID uuid.UUID `json:"club_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RankFetchPointByClubIDAndUserID(ctx context.Context, arg RankFetchPointByClubIDAndUserIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, rankFetchPointByClubIDAndUserID, arg.ClubID, arg.UserID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const rankFetchPointByUserID = `-- name: RankFetchPointByUserID :one
SELECT COALESCE(SUM(r.point),0)::int as total FROM ranks as r
INNER JOIN event_registrations as er ON er.id = r.event_registration_id
INNER JOIN event_participants as ep ON ep.event_registration_id = er.id
WHERE ep.user_id = $1
`

func (q *Queries) RankFetchPointByUserID(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, rankFetchPointByUserID, userID)
	var total int32
	err := row.Scan(&total)
	return total, err
}
