// Code generated by sqlc. DO NOT EDIT.
// source: sport.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const sportCheckOne = `-- name: SportCheckOne :one
SELECT name FROM sports WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) SportCheckOne(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, sportCheckOne, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const sportCreate = `-- name: SportCreate :exec
INSERT INTO sports(name, description, type, thumbnail, updated_at) VALUES ($1, $2, $3, $4, NOW())
`

type SportCreateParams struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Type        SportType `json:"type"`
	Thumbnail   string    `json:"thumbnail"`
}

func (q *Queries) SportCreate(ctx context.Context, arg SportCreateParams) error {
	_, err := q.db.ExecContext(ctx, sportCreate,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Thumbnail,
	)
	return err
}

const sportDelete = `-- name: SportDelete :exec
UPDATE sports SET deleted_at = NOW() WHERE id = $1
`

func (q *Queries) SportDelete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, sportDelete, id)
	return err
}

const sportUpdate = `-- name: SportUpdate :exec
UPDATE sports SET name = $1,
                  description = $2,
                  type = $3,
                  thumbnail = $4,
                  updated_at = NOW()
WHERE id = $5
`

type SportUpdateParams struct {
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Type        SportType `json:"type"`
	Thumbnail   string    `json:"thumbnail"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) SportUpdate(ctx context.Context, arg SportUpdateParams) error {
	_, err := q.db.ExecContext(ctx, sportUpdate,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.Thumbnail,
		arg.ID,
	)
	return err
}
