// Code generated by sqlc. DO NOT EDIT.
// source: test.sql

package db

import (
	"context"
)

const testFetchOne = `-- name: TestFetchOne :one
SELECT id, uuid, name, created_at, updated_at FROM test WHERE id = $1 LIMIT 1
`

func (q *Queries) TestFetchOne(ctx context.Context, id int32) (Test, error) {
	row := q.db.QueryRowContext(ctx, testFetchOne, id)
	var i Test
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
