// Code generated by sqlc. DO NOT EDIT.
// source: user.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const userCountAll = `-- name: UserCountAll :one
SELECT COUNT(id) FROM users where status = TRUE
`

func (q *Queries) UserCountAll(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, userCountAll)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const userCreate = `-- name: UserCreate :one
INSERT INTO users(name, phone, photo, born_at, born_on, identity_number, gender, about, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())
RETURNING id
`

type UserCreateParams struct {
	Name           string       `json:"name"`
	Phone          string       `json:"phone"`
	Photo          string       `json:"photo"`
	BornAt         string       `json:"born_at"`
	BornOn         sql.NullTime `json:"born_on"`
	IdentityNumber string       `json:"identity_number"`
	Gender         string       `json:"gender"`
	About          string       `json:"about"`
}

func (q *Queries) UserCreate(ctx context.Context, arg UserCreateParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, userCreate,
		arg.Name,
		arg.Phone,
		arg.Photo,
		arg.BornAt,
		arg.BornOn,
		arg.IdentityNumber,
		arg.Gender,
		arg.About,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const userFetchAll = `-- name: UserFetchAll :many
SELECT id, name, role, created_at FROM users
ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type UserFetchAllParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type UserFetchAllRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Role      Role      `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) UserFetchAll(ctx context.Context, arg UserFetchAllParams) ([]UserFetchAllRow, error) {
	rows, err := q.db.QueryContext(ctx, userFetchAll, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserFetchAllRow{}
	for rows.Next() {
		var i UserFetchAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userFetchBasicInformation = `-- name: UserFetchBasicInformation :one
SELECT id, name, born_at, born_on, identity_number, phone, photo, gender, about, status, can_participate FROM users
WHERE id = $1
`

type UserFetchBasicInformationRow struct {
	ID             uuid.UUID    `json:"id"`
	Name           string       `json:"name"`
	BornAt         string       `json:"born_at"`
	BornOn         sql.NullTime `json:"born_on"`
	IdentityNumber string       `json:"identity_number"`
	Phone          string       `json:"phone"`
	Photo          string       `json:"photo"`
	Gender         string       `json:"gender"`
	About          string       `json:"about"`
	Status         bool         `json:"status"`
	CanParticipate bool         `json:"can_participate"`
}

func (q *Queries) UserFetchBasicInformation(ctx context.Context, id uuid.UUID) (UserFetchBasicInformationRow, error) {
	row := q.db.QueryRowContext(ctx, userFetchBasicInformation, id)
	var i UserFetchBasicInformationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BornAt,
		&i.BornOn,
		&i.IdentityNumber,
		&i.Phone,
		&i.Photo,
		&i.Gender,
		&i.About,
		&i.Status,
		&i.CanParticipate,
	)
	return i, err
}

const userFetchByKeyword = `-- name: UserFetchByKeyword :many
SELECT DISTINCT users.id, users.name, accounts.username FROM users
INNER JOIN accounts ON accounts.user_id = users.id
WHERE users.role = 'user' AND users.id != $1 AND users.name LIKE $2 OR accounts.username LIKE $3 LIMIT $4
`

type UserFetchByKeywordParams struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Username string    `json:"username"`
	Limit    int32     `json:"limit"`
}

type UserFetchByKeywordRow struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Username string    `json:"username"`
}

func (q *Queries) UserFetchByKeyword(ctx context.Context, arg UserFetchByKeywordParams) ([]UserFetchByKeywordRow, error) {
	rows, err := q.db.QueryContext(ctx, userFetchByKeyword,
		arg.ID,
		arg.Name,
		arg.Username,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserFetchByKeywordRow{}
	for rows.Next() {
		var i UserFetchByKeywordRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userFetchInID = `-- name: UserFetchInID :many
SELECT id, name, gender, can_participate FROM users WHERE id = ANY($1)
`

type UserFetchInIDRow struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	Gender         string    `json:"gender"`
	CanParticipate bool      `json:"can_participate"`
}

func (q *Queries) UserFetchInID(ctx context.Context, id uuid.UUID) ([]UserFetchInIDRow, error) {
	rows, err := q.db.QueryContext(ctx, userFetchInID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserFetchInIDRow{}
	for rows.Next() {
		var i UserFetchInIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Gender,
			&i.CanParticipate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userFetchNameByID = `-- name: UserFetchNameByID :one
SELECT name FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) UserFetchNameByID(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, userFetchNameByID, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const userFetchOne = `-- name: UserFetchOne :one
SELECT users.id, accounts.id as account_id, users.name, users.photo, accounts.username, accounts.type, users.role
FROM users
INNER JOIN accounts ON accounts.user_id = users.id
WHERE accounts.username = $1
ORDER BY array_position(array['manual', 'google', 'facebook']::account_type[] , accounts.type)
LIMIT 1
`

type UserFetchOneRow struct {
	ID        uuid.UUID   `json:"id"`
	AccountID int64       `json:"account_id"`
	Name      string      `json:"name"`
	Photo     string      `json:"photo"`
	Username  string      `json:"username"`
	Type      AccountType `json:"type"`
	Role      Role        `json:"role"`
}

func (q *Queries) UserFetchOne(ctx context.Context, username string) (UserFetchOneRow, error) {
	row := q.db.QueryRowContext(ctx, userFetchOne, username)
	var i UserFetchOneRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Photo,
		&i.Username,
		&i.Type,
		&i.Role,
	)
	return i, err
}

const userFetchOneTypeManual = `-- name: UserFetchOneTypeManual :one
SELECT users.id, accounts.id as account_id, users.name, users.photo, accounts.username, accounts.type, users.role
FROM users
         INNER JOIN accounts ON accounts.user_id = users.id
WHERE accounts.username = $1 AND accounts.type = 'manual'
LIMIT 1
`

type UserFetchOneTypeManualRow struct {
	ID        uuid.UUID   `json:"id"`
	AccountID int64       `json:"account_id"`
	Name      string      `json:"name"`
	Photo     string      `json:"photo"`
	Username  string      `json:"username"`
	Type      AccountType `json:"type"`
	Role      Role        `json:"role"`
}

func (q *Queries) UserFetchOneTypeManual(ctx context.Context, username string) (UserFetchOneTypeManualRow, error) {
	row := q.db.QueryRowContext(ctx, userFetchOneTypeManual, username)
	var i UserFetchOneTypeManualRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.Photo,
		&i.Username,
		&i.Type,
		&i.Role,
	)
	return i, err
}

const userFetchPhotoByID = `-- name: UserFetchPhotoByID :one
SELECT photo FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) UserFetchPhotoByID(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, userFetchPhotoByID, id)
	var photo string
	err := row.Scan(&photo)
	return photo, err
}

const userUpdateBasicInformation = `-- name: UserUpdateBasicInformation :exec
UPDATE users SET name = $1,
                 born_at = $2,
                 born_on = $3,
                 identity_number = $4,
                 phone = $5,
                 photo = $6,
                 gender = $7,
                 about = $8,
                 can_participate = TRUE,
                 updated_at = NOW()
WHERE id = $9
`

type UserUpdateBasicInformationParams struct {
	Name           string       `json:"name"`
	BornAt         string       `json:"born_at"`
	BornOn         sql.NullTime `json:"born_on"`
	IdentityNumber string       `json:"identity_number"`
	Phone          string       `json:"phone"`
	Photo          string       `json:"photo"`
	Gender         string       `json:"gender"`
	About          string       `json:"about"`
	ID             uuid.UUID    `json:"id"`
}

func (q *Queries) UserUpdateBasicInformation(ctx context.Context, arg UserUpdateBasicInformationParams) error {
	_, err := q.db.ExecContext(ctx, userUpdateBasicInformation,
		arg.Name,
		arg.BornAt,
		arg.BornOn,
		arg.IdentityNumber,
		arg.Phone,
		arg.Photo,
		arg.Gender,
		arg.About,
		arg.ID,
	)
	return err
}
