// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase.go
//
// Generated by this command:
//
//	mockgen -source=./usecase.go -destination=../../mocks/event/usecase_mock.go
//

// Package mock_event is a generated GoMock package.
package mock_event

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	db "github.com/project-ippl-dev/tanding-api/internal/db"
	event "github.com/project-ippl-dev/tanding-api/internal/event"
	tools "github.com/project-ippl-dev/tanding-api/internal/tools"
	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// Assign mocks base method.
func (m *MockUsecase) Assign(ctx context.Context, req event.AssignRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Assign", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Assign indicates an expected call of Assign.
func (mr *MockUsecaseMockRecorder) Assign(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assign", reflect.TypeOf((*MockUsecase)(nil).Assign), ctx, req)
}

// CommitteeDelete mocks base method.
func (m *MockUsecase) CommitteeDelete(ctx context.Context, arg event.DeleteCommitteeParams, userID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitteeDelete", ctx, arg, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitteeDelete indicates an expected call of CommitteeDelete.
func (mr *MockUsecaseMockRecorder) CommitteeDelete(ctx, arg, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitteeDelete", reflect.TypeOf((*MockUsecase)(nil).CommitteeDelete), ctx, arg, userID)
}

// CommitteeFetchAll mocks base method.
func (m *MockUsecase) CommitteeFetchAll(ctx context.Context, eventID uuid.UUID) ([]db.EventPrivilegeFetchAllRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitteeFetchAll", ctx, eventID)
	ret0, _ := ret[0].([]db.EventPrivilegeFetchAllRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitteeFetchAll indicates an expected call of CommitteeFetchAll.
func (mr *MockUsecaseMockRecorder) CommitteeFetchAll(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitteeFetchAll", reflect.TypeOf((*MockUsecase)(nil).CommitteeFetchAll), ctx, eventID)
}

// CommitteeUpdate mocks base method.
func (m *MockUsecase) CommitteeUpdate(ctx context.Context, arg event.UpdateCommitteeParams, userID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitteeUpdate", ctx, arg, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitteeUpdate indicates an expected call of CommitteeUpdate.
func (mr *MockUsecaseMockRecorder) CommitteeUpdate(ctx, arg, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitteeUpdate", reflect.TypeOf((*MockUsecase)(nil).CommitteeUpdate), ctx, arg, userID)
}

// Delete mocks base method.
func (m *MockUsecase) Delete(ctx context.Context, eventID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUsecaseMockRecorder) Delete(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUsecase)(nil).Delete), ctx, eventID)
}

// FetchAll mocks base method.
func (m *MockUsecase) FetchAll(ctx context.Context, page, pageSize int32) (tools.Pagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAll", ctx, page, pageSize)
	ret0, _ := ret[0].(tools.Pagination)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAll indicates an expected call of FetchAll.
func (mr *MockUsecaseMockRecorder) FetchAll(ctx, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAll", reflect.TypeOf((*MockUsecase)(nil).FetchAll), ctx, page, pageSize)
}

// FetchByUser mocks base method.
func (m *MockUsecase) FetchByUser(ctx context.Context, page, pageSize int32, userID string) (tools.Pagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchByUser", ctx, page, pageSize, userID)
	ret0, _ := ret[0].(tools.Pagination)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchByUser indicates an expected call of FetchByUser.
func (mr *MockUsecaseMockRecorder) FetchByUser(ctx, page, pageSize, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchByUser", reflect.TypeOf((*MockUsecase)(nil).FetchByUser), ctx, page, pageSize, userID)
}

// FetchInfinite mocks base method.
func (m *MockUsecase) FetchInfinite(ctx context.Context, limit int32, args event.FetchInfiniteQueryParams) (event.ResponseInfinite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchInfinite", ctx, limit, args)
	ret0, _ := ret[0].(event.ResponseInfinite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchInfinite indicates an expected call of FetchInfinite.
func (mr *MockUsecaseMockRecorder) FetchInfinite(ctx, limit, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchInfinite", reflect.TypeOf((*MockUsecase)(nil).FetchInfinite), ctx, limit, args)
}

// FetchOne mocks base method.
func (m *MockUsecase) FetchOne(ctx context.Context, eventID uuid.UUID, userID string) (event.ResponseFetchOne, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOne", ctx, eventID, userID)
	ret0, _ := ret[0].(event.ResponseFetchOne)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOne indicates an expected call of FetchOne.
func (mr *MockUsecaseMockRecorder) FetchOne(ctx, eventID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOne", reflect.TypeOf((*MockUsecase)(nil).FetchOne), ctx, eventID, userID)
}

// Store mocks base method.
func (m *MockUsecase) Store(ctx context.Context, req event.Request, decoded tools.JWT) (int, uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, req, decoded)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(uuid.UUID)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Store indicates an expected call of Store.
func (mr *MockUsecaseMockRecorder) Store(ctx, req, decoded any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockUsecase)(nil).Store), ctx, req, decoded)
}

// Update mocks base method.
func (m *MockUsecase) Update(ctx context.Context, req event.Request, eventID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req, eventID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUsecaseMockRecorder) Update(ctx, req, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUsecase)(nil).Update), ctx, req, eventID)
}

// UpdateRemark mocks base method.
func (m *MockUsecase) UpdateRemark(ctx context.Context, arg event.UpdateRemarkParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRemark", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRemark indicates an expected call of UpdateRemark.
func (mr *MockUsecaseMockRecorder) UpdateRemark(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRemark", reflect.TypeOf((*MockUsecase)(nil).UpdateRemark), ctx, arg)
}

// UpdateStatus mocks base method.
func (m *MockUsecase) UpdateStatus(ctx context.Context, req event.StatusReq, eventID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, req, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockUsecaseMockRecorder) UpdateStatus(ctx, req, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockUsecase)(nil).UpdateStatus), ctx, req, eventID)
}
