// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase.go
//
// Generated by this command:
//
//	mockgen -source=./usecase.go -destination=../../mocks/accomplishment/usecase_mock.go
//

// Package mock_accomplishment is a generated GoMock package.
package mock_accomplishment

import (
	context "context"
	reflect "reflect"

	accomplishment "github.com/project-ippl-dev/tanding-api/internal/accomplishment"
	tools "github.com/project-ippl-dev/tanding-api/internal/tools"
	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockUsecase) Delete(ctx context.Context, userID string, accomplishmentID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, accomplishmentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUsecaseMockRecorder) Delete(ctx, userID, accomplishmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUsecase)(nil).Delete), ctx, userID, accomplishmentID)
}

// FetchAll mocks base method.
func (m *MockUsecase) FetchAll(ctx context.Context, page, pageSize int32, userID string) (tools.Pagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAll", ctx, page, pageSize, userID)
	ret0, _ := ret[0].(tools.Pagination)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAll indicates an expected call of FetchAll.
func (mr *MockUsecaseMockRecorder) FetchAll(ctx, page, pageSize, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAll", reflect.TypeOf((*MockUsecase)(nil).FetchAll), ctx, page, pageSize, userID)
}

// Store mocks base method.
func (m *MockUsecase) Store(ctx context.Context, req accomplishment.Request, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, req, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockUsecaseMockRecorder) Store(ctx, req, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockUsecase)(nil).Store), ctx, req, userID)
}

// Update mocks base method.
func (m *MockUsecase) Update(ctx context.Context, req accomplishment.Request, userID string, accomplishmentID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req, userID, accomplishmentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUsecaseMockRecorder) Update(ctx, req, userID, accomplishmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUsecase)(nil).Update), ctx, req, userID, accomplishmentID)
}
